//! Validate DID-binding `control_proof` payloads against the resolved DID
//! document.
//!
//! Shape: a compact JWS signed by one of the DID's verification-method
//! keys, with an attached canonical "binding statement" payload of the form:
//!
//! ```json
//! {
//!   "schema": "ak.schema.did_binding_control_proof.v1",
//!   "account_did": "<account DID>",
//!   "verification_method": "<DID URL from verificationMethod.id>",
//!   "audience": "<local coauth service DID>",
//!   "trust_domain": "<local deployment ak:trust_domain:...>",
//!   "nonce": "<opaque single-use nonce>",
//!   "iat": "<RFC3339 timestamp>",
//!   "exp": "<RFC3339 timestamp; exp - iat <= 300s>"
//! }
//! ```
//!
//! Replay boundary (identity-did §5.1 / §3.6, conformance vector
//! `ak.vector.identity.did_proof_replay_window.v1`):
//!   - `audience` MUST equal the local coauth service DID, so a proof minted for another receiver
//!     cannot be relayed here.
//!   - `trust_domain` MUST equal this deployment's trust domain, so the identical proof bytes
//!     cannot be carried from deployment A to deployment B (`cross_domain_replay_rejected`).
//!   - `iat` skew vs. server clock MUST be within ±300s and the freshness window `exp - iat` MUST
//!     be ≤ 300s (an issuer cannot widen its own replay window).
//!   - `nonce` MUST be single-use: a successful validation consumes it in the process-global
//!     [`NonceStore`], so the same proof cannot be resubmitted inside the ±300s window.
//!
//! To be confirmed (server-issued challenge): §5.1 step 3 also requires the
//! challenge/nonce to be **generated by the Auth Server** rather than
//! echoed from the request body. That full challenge-response strand needs
//! a new issue endpoint plus persisted challenge state and is tracked
//! separately (see module note below). The audience / trust_domain /
//! freshness / single-use-nonce closure landed here is the part that can
//! be enforced without new wire surface.
//!
//! Verification strand:
//!   1. Resolve the DID via the configured resolver chain (`DidResolverService`).
//!   2. Reject if the resolver returns no `verificationMethod` keys.
//!   3. Require the JWS `kid`, statement `verification_method`, and resolved DID document
//!      `verificationMethod.id` to match exactly.
//!   4. Reject if the JWS doesn't verify against that exact method key.
//!   5. Reject if the attached payload bytes are not the canonical JSON encoding of the decoded
//!      binding statement.
//!   6. Reject if the embedded binding statement doesn't match the request (`account_did` + nonce
//!      both match exactly).
//!
//! SDK integration: signature verification is performed by
//! `arkret_signatures::proof::verify_detached_ed25519_signature`, which
//! routes Ed25519 checks through the SDK's strict verifier. The compact JWS
//! envelope is parsed locally (header.payload.signature segments) and the
//! canonical signing input is recomputed from the wire bytes so no JWS library
//! state intervenes between the resolved DID-document JWK and the SDK verifier.
//! The embedded coauth_jose `jwt.verify_with_jwks(...)` path has been removed;
//! coauth_jose's JWT parser is still used to extract the typed
//! `BindingStatementClaims` / `VerificationServiceProofClaims` payload.
//!
//! ## Verification-service proof
//!
//! [`verify_verification_service_proof`] is the sister verifier for the
//! 3PID invite chain (see `third_party_invite::verify_invite`). It
//! validates a signed JWT issued by a trusted 3PID verification service
//! whose claims attest that a 3PID (e.g. email) was verified for the
//! presented invite. Required claims: `iss` (must be a member of the
//! configured verification-service allowlist — SEC-07a), `aud` (must equal the
//! local coauth service DID), `sub` (SHA-256 hex of the normalized 3PID),
//! `exp` (must be in the future), `nbf` (must be ≤ now), `jti`, and
//! `nonce`. The signature is verified against the verification
//! service's resolved DID document JWKS.

use arkret_core::canonical::canonical_json_bytes;
use arkret_signatures::proof::verify_detached_ed25519_signature;
use base64ct::{Base64UrlUnpadded, Encoding as _};
use chrono::{DateTime, Utc};
use coauth_config::ArkretConfig;
use coauth_data::{BoxRepository, UrlBuilder};
use coauth_iana::jose::JsonWebSignatureAlg;
use coauth_jose::jwt::{JsonWebSignatureHeader, Jwt};
use coauth_keystore::Keystore;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::services::did_resolver::{
    DidResolution, DidResolutionIdentityFactRejection, DidResolveError, DidResolverService,
};

pub const DID_BINDING_CONTROL_PROOF_SCHEMA: &str = "ak.schema.did_binding_control_proof.v1";

/// Canonical binding statement claims embedded in a proof JWS.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BindingStatementClaims {
    /// Schema discriminator. Must equal
    /// `ak.schema.did_binding_control_proof.v1`.
    pub schema: String,
    /// The DID being bound.
    pub account_did: String,
    /// DID URL of the resolved verification method that signs the proof.
    pub verification_method: String,
    /// Receiver binding — MUST equal the local coauth service DID. Stops
    /// a proof minted for a different receiver from being relayed here
    /// (identity-did §5.1 audience/origin binding).
    pub audience: String,
    /// Deployment binding — MUST equal this deployment's `trust_domain`.
    /// Stops identical proof bytes being carried across deployments
    /// (identity-did §3.6 `cross_domain_replay_rejected`).
    pub trust_domain: String,
    /// Single-use nonce supplied in the binding request. Consumed on
    /// successful validation so it cannot be replayed in the freshness
    /// window.
    pub nonce: String,
    /// Issuance time. `|iat - now|` MUST be within ±300s of the server
    /// clock.
    pub iat: DateTime<Utc>,
    /// Expiry. `exp - iat` MUST be ≤ 300s (max-freshness window) and the
    /// proof MUST be rejected once `now >= exp`.
    pub exp: DateTime<Utc>,
}

pub struct ValidatedDidBindingControlProof {
    pub claims: BindingStatementClaims,
    pub resolution: DidResolution,
}

/// Validation errors. All variants are deterministic from the inputs and
/// resolver response.
#[derive(Debug, Error)]
pub enum DidBindingProofError {
    #[error("control_proof must be a non-empty JWS string")]
    EmptyProof,

    #[error("control_proof JWS could not be parsed: {0}")]
    InvalidJws(String),

    #[error("DID resolver failed: {0}")]
    Resolve(#[from] DidResolveError),

    #[error("DID document has no verificationMethod entries")]
    NoVerificationKey,

    #[error("DID resolver result is not acceptable as a full identity fact: {0:?}")]
    ResolverNotFullIdentityFact(DidResolutionIdentityFactRejection),

    #[error("control_proof JWS header is missing a verificationMethod kid")]
    MissingVerificationMethod,

    #[error("control_proof JWS alg must be EdDSA, got {0}")]
    UnsupportedAlgorithm(String),

    #[error("control_proof verificationMethod does not match the binding statement")]
    VerificationMethodMismatch,

    #[error("control_proof verificationMethod is not present in the resolved DID document")]
    VerificationMethodNotFound,

    #[error("control_proof JWS signature did not verify against the resolved verificationMethod")]
    SignatureMismatch,

    #[error("binding statement canonical JSON could not be encoded: {0}")]
    CanonicalStatement(String),

    #[error("binding statement payload is not the canonical JSON encoding of the decoded claims")]
    CanonicalStatementMismatch,

    #[error("binding statement schema discriminator mismatch")]
    StatementSchemaMismatch,

    #[error("binding statement account_did does not match request")]
    AccountDidMismatch,

    #[error("binding statement nonce does not match request")]
    NonceMismatch,

    #[error("binding statement audience does not match local service DID")]
    AudienceMismatch,

    #[error("binding statement trust_domain does not match local deployment")]
    TrustDomainMismatch,

    #[error("binding statement iat is in the future or expired")]
    IatOutOfRange,

    #[error("binding statement freshness window exp - iat exceeds 300s or exp precedes iat")]
    FreshnessWindowExceeded,

    #[error("binding statement has expired (now >= exp)")]
    ProofExpired,

    #[error("binding statement nonce has already been used")]
    NonceReplayed,
}

/// Maximum `iat` skew accepted, in seconds. Past or future drift beyond
/// this window rejects the proof (identity-did §5.1: SHOULD ≤ 300s).
const MAX_IAT_SKEW_SECS: i64 = 5 * 60;

/// Maximum freshness window, in seconds. `exp - iat` beyond this rejects
/// the proof so an issuer cannot widen its own replay window
/// (identity-did §5.1: SHOULD ≤ 300s).
const MAX_FRESHNESS_SECS: i64 = 5 * 60;

/// Normalize a DID for any binding-write path: trim whitespace, then run
/// the value through the SDK `Did::new` validator (which enforces the
/// Round-4 `^did:[a-z0-9]+:[^\s]+$` regex).
///
/// Returns the normalized DID string on success, or
/// `DidBindingProofError::InvalidJws` on rejection (re-using the
/// existing error variant so the wire surface stays stable).
///
/// Phase P2 (B-D): all DID binding writes MUST round-trip through this
/// helper. The SDK validator is the single source of truth — coauth does
/// not maintain its own regex.
pub fn normalize_did_for_binding(did: &str) -> Result<String, DidBindingProofError> {
    let trimmed = did.trim();
    if trimmed.is_empty() {
        return Err(DidBindingProofError::InvalidJws(
            "did must be a non-empty DID URI".to_owned(),
        ));
    }
    if arkret_core::Did::new(trimmed.to_owned()).is_err() {
        return Err(DidBindingProofError::InvalidJws(format!(
            "did {trimmed:?} fails round-4 DID regex (^did:[a-z0-9]+:[^\\s]+$)"
        )));
    }
    // `did:uuid` is a valid identifier method (accepted by `Did::new`) but is
    // not a resolvable identity method: a binding proof MUST reference a DID
    // whose controller key can be resolved (web / webvh / key / plc), so uuid
    // is rejected on this path (Round 4 reserves it).
    if trimmed.starts_with("did:uuid:") {
        return Err(DidBindingProofError::InvalidJws(
            "did:uuid is not a resolvable binding-proof DID method".to_owned(),
        ));
    }
    Ok(trimmed.to_owned())
}

fn ensure_full_identity_fact_resolution(
    resolution: &DidResolution,
) -> Result<(), DidResolutionIdentityFactRejection> {
    match resolution.identity_fact_rejection() {
        Some(rejection) => Err(rejection),
        None => Ok(()),
    }
}

/// Validate a `control_proof` JWS against the resolved DID document and
/// the requested binding statement.
///
/// `schema` / `account_did` / `nonce` form the canonical statement
/// that must be embedded inside the JWS payload. `now` is used to bound
/// the `iat` / `exp` claims (skew ±300s, freshness window ≤ 300s).
///
/// `expected_audience` MUST equal the local coauth service DID and
/// `expected_trust_domain` the local deployment trust domain; both are
/// matched byte-for-byte against the statement to close cross-receiver /
/// cross-deployment replay (identity-did §5.1 / §3.6).
///
/// `nonce_store` is consumed on success: the statement `nonce` is
/// recorded (keyed by `(audience, trust_domain, account_did, nonce)`)
/// until `exp`, so a second submission of the same proof inside the
/// freshness window is rejected as a replay.
#[allow(clippy::too_many_arguments)]
pub async fn validate_control_proof(
    http_client: &reqwest::Client,
    url_builder: &UrlBuilder,
    arkret_config: &ArkretConfig,
    key_store: &Keystore,
    repo: &mut BoxRepository,
    did_resolver: &dyn DidResolverService,
    nonce_store: &crate::services::third_party_invite::NonceStore,
    proof_jws: &str,
    account_did: &str,
    nonce: &str,
    expected_audience: &str,
    expected_trust_domain: &str,
    now: DateTime<Utc>,
) -> Result<ValidatedDidBindingControlProof, DidBindingProofError> {
    if proof_jws.trim().is_empty() {
        return Err(DidBindingProofError::EmptyProof);
    }

    // Round 4 (spec a77b995) — DID regex tightened to
    // `^did:[a-z0-9]+:[^\s]+$`. Reject any value the SDK validator
    // refuses BEFORE invoking the resolver chain, so wire-broken DIDs
    // never trigger network I/O. Delegating to the SDK's validator
    // keeps coauth in lockstep with the canonical regex.
    if arkret_core::Did::new(account_did.to_owned()).is_err() {
        return Err(DidBindingProofError::InvalidJws(format!(
            "account_did {account_did:?} fails round-4 DID regex"
        )));
    }

    // Parse JWS
    let jwt: Jwt<'_, BindingStatementClaims> =
        Jwt::try_from(proof_jws).map_err(|e| DidBindingProofError::InvalidJws(e.to_string()))?;
    if jwt.header().alg() != &JsonWebSignatureAlg::EdDsa {
        return Err(DidBindingProofError::UnsupportedAlgorithm(
            jwt.header().alg().to_string(),
        ));
    }
    let payload_bytes = decode_attached_jws_payload(proof_jws)?;
    let verification_method = jwt
        .header()
        .kid()
        .ok_or(DidBindingProofError::MissingVerificationMethod)?
        .to_owned();

    let claims = jwt.payload();
    if claims.verification_method != verification_method {
        return Err(DidBindingProofError::VerificationMethodMismatch);
    }
    validate_canonical_statement_payload(&payload_bytes, claims)?;

    // Resolve DID document
    let resolution = did_resolver
        .resolve_did_document(
            http_client,
            url_builder,
            arkret_config,
            key_store,
            repo,
            account_did,
        )
        .await?;
    ensure_full_identity_fact_resolution(&resolution)
        .map_err(DidBindingProofError::ResolverNotFullIdentityFact)?;

    let verification_methods = &resolution.document.verification_method;
    if verification_methods.is_empty() {
        return Err(DidBindingProofError::NoVerificationKey);
    }

    verify_compact_jws_with_sdk(proof_jws, verification_methods, &verification_method)
        .map_err(|_| DidBindingProofError::SignatureMismatch)?;

    validate_binding_statement_claims(
        claims,
        account_did,
        nonce,
        expected_audience,
        expected_trust_domain,
        now,
    )?;

    // Single-use nonce consumption — runs only after every other check
    // passes, so a replayed/garbage proof can never poison the store
    // before its signature is verified (same ordering rule as the 3PID
    // invite chain). The key embeds audience + trust_domain + account_did
    // so distinct receivers / deployments / DIDs cannot collide on a
    // shared nonce value.
    let replay_key = format!(
        "{}|{}|{}|{}|{}",
        DID_BINDING_CONTROL_PROOF_SCHEMA,
        claims.audience,
        claims.trust_domain,
        claims.account_did,
        claims.nonce
    );
    nonce_store
        .check_and_record(&replay_key, claims.exp, now)
        .map_err(|_| DidBindingProofError::NonceReplayed)?;

    Ok(ValidatedDidBindingControlProof {
        claims: claims.clone(),
        resolution,
    })
}

fn decode_attached_jws_payload(proof_jws: &str) -> Result<Vec<u8>, DidBindingProofError> {
    let mut parts = proof_jws.split('.');
    let _header = parts.next().ok_or_else(|| {
        DidBindingProofError::InvalidJws("compact JWS is missing protected header".to_owned())
    })?;
    let payload = parts.next().ok_or_else(|| {
        DidBindingProofError::InvalidJws("compact JWS is missing payload".to_owned())
    })?;
    let _signature = parts.next().ok_or_else(|| {
        DidBindingProofError::InvalidJws("compact JWS is missing signature".to_owned())
    })?;
    if parts.next().is_some() {
        return Err(DidBindingProofError::InvalidJws(
            "compact JWS has too many segments".to_owned(),
        ));
    }
    if payload.is_empty() {
        return Err(DidBindingProofError::InvalidJws(
            "control_proof must attach the canonical binding statement payload".to_owned(),
        ));
    }

    Base64UrlUnpadded::decode_vec(payload).map_err(|e| {
        DidBindingProofError::InvalidJws(format!("payload base64url decode failed: {e}"))
    })
}

fn validate_canonical_statement_payload(
    payload_bytes: &[u8],
    claims: &BindingStatementClaims,
) -> Result<(), DidBindingProofError> {
    let canonical = canonical_json_bytes(claims)
        .map_err(|e| DidBindingProofError::CanonicalStatement(e.to_string()))?;
    if payload_bytes != canonical.as_slice() {
        return Err(DidBindingProofError::CanonicalStatementMismatch);
    }

    Ok(())
}

/// Error returned by [`verify_compact_jws_with_sdk`]. Kept private to
/// this module — callers map it onto the bound public
/// `DidBindingProofError::SignatureMismatch` /
/// `VerificationProofError::SignatureMismatch` variant.
#[derive(Debug, thiserror::Error)]
pub(crate) enum SdkJwsVerifyError {
    #[error("compact JWS shape is invalid: {0}")]
    InvalidShape(String),
    #[error("compact JWS alg must be EdDSA, got {0}")]
    UnsupportedAlgorithm(String),
    #[error("verification_method '{0}' not present in the resolved DID document")]
    MethodNotFound(String),
    #[error("resolved verification_method JWK is not a supported Ed25519 OKP key: {0}")]
    UnsupportedJwk(String),
    #[error("Ed25519 signature did not verify: {0}")]
    SignatureMismatch(String),
}

/// Verify a compact JWS using the SDK's pure-Rust Ed25519 verifier.
///
/// AKP-0007 P2B.3.1: this replaces the previous embedded
/// `coauth_jose::jwt::Jwt::verify_with_jwks` envelope-verification path.
/// The compact-JWS shape (`header.payload.signature`) is parsed into
/// segment bytes here; the signing input
/// (`b64url(header) "." b64url(payload)`) is reconstructed from the wire
/// bytes themselves so no JWS library state intervenes between the
/// resolved DID-document JWK and the final
/// `arkret_signatures::proof::verify_detached_ed25519_signature` call.
pub(crate) fn verify_compact_jws_with_sdk(
    proof_jws: &str,
    verification_methods: &[crate::handlers::arkret::VerificationMethod],
    verification_method_id: &str,
) -> Result<(), SdkJwsVerifyError> {
    let mut parts = proof_jws.split('.');
    let header_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing protected header".to_owned()))?;
    let payload_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing payload segment".to_owned()))?;
    let signature_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing signature segment".to_owned()))?;
    if parts.next().is_some() {
        return Err(SdkJwsVerifyError::InvalidShape(
            "too many segments".to_owned(),
        ));
    }

    let header_bytes = Base64UrlUnpadded::decode_vec(header_b64u)
        .map_err(|err| SdkJwsVerifyError::InvalidShape(format!("invalid header b64url: {err}")))?;
    let header: JsonWebSignatureHeader = serde_json::from_slice(&header_bytes).map_err(|err| {
        SdkJwsVerifyError::InvalidShape(format!("invalid protected header: {err}"))
    })?;
    if header.alg() != &JsonWebSignatureAlg::EdDsa {
        return Err(SdkJwsVerifyError::UnsupportedAlgorithm(
            header.alg().to_string(),
        ));
    }

    let method = verification_methods
        .iter()
        .find(|method| method.id == verification_method_id)
        .ok_or_else(|| SdkJwsVerifyError::MethodNotFound(verification_method_id.to_owned()))?;

    // RFC 7515 §5.2 signing input: ASCII bytes of "<header_b64u>.<payload_b64u>".
    let mut signing_input = String::with_capacity(header_b64u.len() + 1 + payload_b64u.len());
    signing_input.push_str(header_b64u);
    signing_input.push('.');
    signing_input.push_str(payload_b64u);

    let material = method
        .public_key_material()
        .map_err(SdkJwsVerifyError::UnsupportedJwk)?;
    if verify_detached_ed25519_signature(&material, signing_input.as_bytes(), signature_b64u) {
        Ok(())
    } else {
        Err(SdkJwsVerifyError::SignatureMismatch(
            "Ed25519 signature did not verify".to_owned(),
        ))
    }
}

/// Verify a compact detached JWS (`protected..signature`) over `payload_bytes`
/// using the `kid` verification method from the protected header.
pub(crate) fn verify_detached_jws_with_sdk(
    detached_jws: &str,
    payload_bytes: &[u8],
    verification_methods: &[crate::handlers::arkret::VerificationMethod],
) -> Result<String, SdkJwsVerifyError> {
    let mut parts = detached_jws.split('.');
    let header_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing protected header".to_owned()))?;
    let payload_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing payload segment".to_owned()))?;
    let signature_b64u = parts
        .next()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing signature segment".to_owned()))?;
    if parts.next().is_some() {
        return Err(SdkJwsVerifyError::InvalidShape(
            "too many segments".to_owned(),
        ));
    }
    if !payload_b64u.is_empty() {
        return Err(SdkJwsVerifyError::InvalidShape(
            "detached JWS payload segment must be empty".to_owned(),
        ));
    }

    let header_bytes = Base64UrlUnpadded::decode_vec(header_b64u)
        .map_err(|err| SdkJwsVerifyError::InvalidShape(format!("invalid header b64url: {err}")))?;
    let header: JsonWebSignatureHeader = serde_json::from_slice(&header_bytes).map_err(|err| {
        SdkJwsVerifyError::InvalidShape(format!("invalid protected header: {err}"))
    })?;
    if header.alg() != &JsonWebSignatureAlg::EdDsa {
        return Err(SdkJwsVerifyError::UnsupportedAlgorithm(
            header.alg().to_string(),
        ));
    }
    let verification_method = header
        .kid()
        .ok_or_else(|| SdkJwsVerifyError::InvalidShape("missing kid".to_owned()))?
        .to_owned();

    let attached_payload_b64u = Base64UrlUnpadded::encode_string(payload_bytes);
    let attached = format!("{header_b64u}.{attached_payload_b64u}.{signature_b64u}");
    verify_compact_jws_with_sdk(&attached, verification_methods, &verification_method)?;
    Ok(verification_method)
}

#[allow(clippy::too_many_arguments)]
fn validate_binding_statement_claims(
    claims: &BindingStatementClaims,
    account_did: &str,
    nonce: &str,
    expected_audience: &str,
    expected_trust_domain: &str,
    now: DateTime<Utc>,
) -> Result<(), DidBindingProofError> {
    if claims.schema != DID_BINDING_CONTROL_PROOF_SCHEMA {
        return Err(DidBindingProofError::StatementSchemaMismatch);
    }
    if claims.account_did != account_did {
        return Err(DidBindingProofError::AccountDidMismatch);
    }
    if claims.nonce != nonce {
        return Err(DidBindingProofError::NonceMismatch);
    }
    // §5.1 audience/origin binding: reject a proof minted for a different
    // receiver. Byte-exact, no prefix leniency.
    if claims.audience != expected_audience {
        return Err(DidBindingProofError::AudienceMismatch);
    }
    // §3.6 trust-domain binding: reject a proof carried from another
    // deployment (`cross_domain_replay_rejected`).
    if claims.trust_domain != expected_trust_domain {
        return Err(DidBindingProofError::TrustDomainMismatch);
    }
    // §5.1 skew: `|iat - now|` within ±300s.
    let skew_secs = (claims.iat - now).num_seconds().abs();
    if skew_secs > MAX_IAT_SKEW_SECS {
        return Err(DidBindingProofError::IatOutOfRange);
    }
    // §5.1 freshness window: `exp - iat` within (0, 300s]. An issuer must
    // not be able to widen its own replay window.
    let freshness_secs = (claims.exp - claims.iat).num_seconds();
    if freshness_secs <= 0 || freshness_secs > MAX_FRESHNESS_SECS {
        return Err(DidBindingProofError::FreshnessWindowExceeded);
    }
    // Reject once the proof has expired.
    if now >= claims.exp {
        return Err(DidBindingProofError::ProofExpired);
    }

    Ok(())
}

// ─────────────── Verification-service proof (3PID invite chain)
// ───────────────

/// JWT claims issued by the trusted 3PID verification service.
///
/// All fields are MANDATORY. Unknown / missing claims are rejected
/// up-front via the JSON deserialiser; semantic checks
/// (`iss` / `aud` / `sub` / `exp` / `nbf`) live in
/// [`verify_verification_service_proof`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationServiceProofClaims {
    /// Issuer DID — MUST equal the configured trusted verification
    /// service DID.
    pub iss: String,
    /// Audience — MUST equal the local coauth service DID.
    pub aud: String,
    /// Subject — SHA-256 (hex) of the normalized 3PID (e.g. lowercased
    /// trimmed email address).
    pub sub: String,
    /// Expiry, Unix-epoch seconds. MUST be in the future.
    pub exp: i64,
    /// Not-before, Unix-epoch seconds. MUST be ≤ now.
    pub nbf: i64,
    /// JWT ID. Used for replay defence in the calling layer.
    pub jti: String,
    /// Single-use nonce; the upper layer (`third_party_invite`)
    /// records it for cross-proof linkage.
    pub nonce: String,
}

/// Errors returned by [`verify_verification_service_proof`].
///
/// The caller MAPS these onto the public
/// `InviteVerificationError::VerificationProofInvalid` /
/// `ProofExpired` variants in `third_party_invite.rs`. We keep this
/// enum private to coauth's service layer (i.e. not exposed on the
/// wire) so we can grow it without breaking the HTTP surface.
#[derive(Debug, Error)]
pub enum VerificationProofError {
    #[error("JWS could not be parsed: {0}")]
    InvalidJws(String),
    #[error("DID resolver failed: {0}")]
    Resolve(#[from] DidResolveError),
    #[error("DID document has no verificationMethod entries")]
    NoVerificationKey,

    #[error("DID resolver result is not acceptable as a full identity fact: {0:?}")]
    ResolverNotFullIdentityFact(DidResolutionIdentityFactRejection),
    #[error("JWS header is missing a verificationMethod kid")]
    MissingVerificationMethod,
    #[error("JWS alg must be EdDSA, got {0}")]
    UnsupportedAlgorithm(String),
    #[error("JWS verificationMethod is not present in the resolved DID document")]
    VerificationMethodNotFound,
    #[error("JWS signature did not verify against any verification-service key")]
    SignatureMismatch,
    #[error("iss claim {actual:?} is not in the verification-service allowlist {allowlist:?}")]
    IssuerNotAllowed {
        allowlist: Vec<String>,
        actual: String,
    },
    #[error("aud claim {actual:?} does not match expected audience {expected:?}")]
    AudienceMismatch { expected: String, actual: String },
    #[error("nbf claim {nbf} is in the future (now={now})")]
    NotYetValid { nbf: i64, now: i64 },
    #[error("proof has expired: {0}")]
    Expired(String),
    #[error("sub claim is empty or malformed")]
    SubjectMalformed,
}

/// SEC-07a — exact-match membership test for the verification-service
/// allowlist (`spec/v1/zh/sync/third-party-invites.md` §2.1 / §4.3 step 2a).
/// Returns `true` iff `iss` is byte-for-byte equal to an allowlist member.
/// An empty allowlist always returns `false` (fail closed).
#[must_use]
pub fn issuer_is_allowed(allowlist: &[String], iss: &str) -> bool {
    allowlist.iter().any(|did| did == iss)
}

/// Verify a verification-service proof JWS.
///
/// Steps:
/// 1. Parse the compact JWS into a typed JWT.
/// 2. Reject empty / malformed claims (`sub`).
/// 3. SEC-07a — reject any `iss` not in the verification-service allowlist
///    (`spec/v1/zh/sync/third-party-invites.md` §2.1 / §4.3 step 2a). This membership gate runs
///    *before* the subject proof is checked by the caller, so a valid subject proof can never admit
///    an off-allowlist verifier. Also match `aud` against the expected value.
/// 4. Reject `nbf > now` and `exp <= now`.
/// 5. Resolve the issuer DID document, verify the signature against its JWKS.
///
/// Replay defence (`jti` deduplication) is NOT done here — the caller
/// owns the nonce store so a successful verify against a replayed
/// `jti` doesn't poison the store with garbage entries before the
/// signature is checked.
#[allow(clippy::too_many_arguments)]
pub async fn verify_verification_service_proof(
    http_client: &reqwest::Client,
    url_builder: &UrlBuilder,
    arkret_config: &ArkretConfig,
    key_store: &Keystore,
    repo: &mut BoxRepository,
    did_resolver: &dyn DidResolverService,
    proof_jws: &str,
    expected_issuer_dids: &[String],
    expected_audience: &str,
    now: DateTime<Utc>,
) -> Result<VerificationServiceProofClaims, VerificationProofError> {
    if proof_jws.trim().is_empty() {
        return Err(VerificationProofError::InvalidJws("empty JWS".into()));
    }

    let jwt: Jwt<'_, VerificationServiceProofClaims> =
        Jwt::try_from(proof_jws).map_err(|e| VerificationProofError::InvalidJws(e.to_string()))?;
    if jwt.header().alg() != &JsonWebSignatureAlg::EdDsa {
        return Err(VerificationProofError::UnsupportedAlgorithm(
            jwt.header().alg().to_string(),
        ));
    }

    let claims = jwt.payload();
    if claims.sub.trim().is_empty() {
        return Err(VerificationProofError::SubjectMalformed);
    }
    // SEC-07a / §4.3 step 2a — membership gate. The issuer MUST be in the
    // explicit allowlist; this runs before the caller's subject-proof check,
    // so a valid subject proof can never admit an off-allowlist verifier.
    if !issuer_is_allowed(expected_issuer_dids, &claims.iss) {
        return Err(VerificationProofError::IssuerNotAllowed {
            allowlist: expected_issuer_dids.to_vec(),
            actual: claims.iss.clone(),
        });
    }
    if claims.aud != expected_audience {
        return Err(VerificationProofError::AudienceMismatch {
            expected: expected_audience.to_owned(),
            actual: claims.aud.clone(),
        });
    }
    let now_ts = now.timestamp();
    if claims.nbf > now_ts {
        return Err(VerificationProofError::NotYetValid {
            nbf: claims.nbf,
            now: now_ts,
        });
    }
    if claims.exp <= now_ts {
        return Err(VerificationProofError::Expired(format!(
            "exp {} <= now {}",
            claims.exp, now_ts
        )));
    }

    let verification_method = jwt
        .header()
        .kid()
        .ok_or(VerificationProofError::MissingVerificationMethod)?
        .to_owned();

    // Resolve the issuer DID and check the signature against the exact
    // verificationMethod selected by the protected header.
    let resolution = did_resolver
        .resolve_did_document(
            http_client,
            url_builder,
            arkret_config,
            key_store,
            repo,
            &claims.iss,
        )
        .await?;
    ensure_full_identity_fact_resolution(&resolution)
        .map_err(VerificationProofError::ResolverNotFullIdentityFact)?;

    let verification_methods = &resolution.document.verification_method;
    if verification_methods.is_empty() {
        return Err(VerificationProofError::NoVerificationKey);
    }
    verify_compact_jws_with_sdk(proof_jws, verification_methods, &verification_method)
        .map_err(|_| VerificationProofError::SignatureMismatch)?;

    Ok(claims.clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_AUDIENCE: &str = "did:web:auth.acme.example";
    const TEST_TRUST_DOMAIN: &str = "ak:trust_domain:auth.acme.example";

    fn statement_claims_default() -> BindingStatementClaims {
        let iat = chrono::DateTime::<Utc>::from_timestamp(1_700_000_000, 0).unwrap();
        BindingStatementClaims {
            schema: DID_BINDING_CONTROL_PROOF_SCHEMA.to_owned(),
            account_did: "did:web:alice.example".to_owned(),
            verification_method: "did:web:alice.example#key-1".to_owned(),
            audience: TEST_AUDIENCE.to_owned(),
            trust_domain: TEST_TRUST_DOMAIN.to_owned(),
            nonce: "nonce-123".to_owned(),
            iat,
            exp: iat + chrono::Duration::seconds(MAX_FRESHNESS_SECS),
        }
    }

    fn resolution_with_identity_fact_rejection(
        rejection: DidResolutionIdentityFactRejection,
    ) -> DidResolution {
        DidResolution {
            document: crate::handlers::arkret::DidDocument {
                id: "did:webvh:ztest:resolver.example:users:alice".to_owned(),
                also_known_as: Vec::new(),
                verification_method: Vec::new(),
                authentication: Vec::new(),
                assertion_method: Vec::new(),
                capability_delegation: Vec::new(),
                service: Vec::new(),
                metadata: None,
            },
            source: crate::services::did_resolver::DidResolutionSource::DelegatedResolver,
            verified_local_binding: false,
            key_log_head: None,
            method_evidence: serde_json::json!({"resolver_state": "webvh_cache_only_degraded"}),
            identity_fact_rejection: Some(rejection),
        }
    }

    #[test]
    fn degraded_resolution_cannot_back_full_identity_or_verification_facts() {
        let resolution = resolution_with_identity_fact_rejection(
            DidResolutionIdentityFactRejection::CacheOnlyDegraded,
        );

        let binding_err = ensure_full_identity_fact_resolution(&resolution)
            .map_err(DidBindingProofError::ResolverNotFullIdentityFact)
            .expect_err("degraded resolver must not back DID binding proof success");
        assert!(matches!(
            binding_err,
            DidBindingProofError::ResolverNotFullIdentityFact(
                DidResolutionIdentityFactRejection::CacheOnlyDegraded
            )
        ));

        let verification_err = ensure_full_identity_fact_resolution(&resolution)
            .map_err(VerificationProofError::ResolverNotFullIdentityFact)
            .expect_err("degraded resolver must not back verification-service proof success");
        assert!(matches!(
            verification_err,
            VerificationProofError::ResolverNotFullIdentityFact(
                DidResolutionIdentityFactRejection::CacheOnlyDegraded
            )
        ));
    }

    #[test]
    fn issuer_allowlist_membership_gate() {
        // SEC-07a / §4.3 step 2a — only allowlisted issuers pass.
        let allowlist = vec![
            "did:web:a.example".to_owned(),
            "did:web:b.example".to_owned(),
        ];
        // Membership hit → allowed.
        assert!(issuer_is_allowed(&allowlist, "did:web:a.example"));
        assert!(issuer_is_allowed(&allowlist, "did:web:b.example"));
        // Off-allowlist issuer → rejected (must not be admitted by any
        // later subject-proof check).
        assert!(!issuer_is_allowed(&allowlist, "did:web:evil.example"));
        // Byte-exact: no prefix / substring leniency.
        assert!(!issuer_is_allowed(&allowlist, "did:web:a.example#key-1"));
        // Empty allowlist → fail closed.
        assert!(!issuer_is_allowed(&[], "did:web:a.example"));
    }

    #[test]
    fn binding_statement_claims_round_trip() {
        let original = statement_claims_default();
        let json = serde_json::to_string(&original).unwrap();
        let decoded: BindingStatementClaims = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.schema, original.schema);
        assert_eq!(decoded.account_did, original.account_did);
        assert_eq!(decoded.verification_method, original.verification_method);
        assert_eq!(decoded.audience, original.audience);
        assert_eq!(decoded.trust_domain, original.trust_domain);
        assert_eq!(decoded.nonce, original.nonce);
        assert_eq!(decoded.iat, original.iat);
        assert_eq!(decoded.exp, original.exp);
    }

    #[test]
    fn binding_statement_schema_must_be_explicit() {
        // Sanity check: schema discriminator literal is what the validator expects.
        assert_eq!(
            statement_claims_default().schema,
            DID_BINDING_CONTROL_PROOF_SCHEMA
        );
    }

    /// Phase P2 (B-D) regression: every DID-binding write path MUST
    /// reject non-canonical DID forms BEFORE persistence. Wire shape is
    /// the SDK's Round-4 regex `^did:[a-z0-9]+:[^\s]+$`.
    #[test]
    fn normalize_did_for_binding_enforces_round4_regex() {
        // Accepted canonical forms.
        assert_eq!(
            normalize_did_for_binding("did:web:alice.example").unwrap(),
            "did:web:alice.example"
        );
        assert_eq!(
            normalize_did_for_binding("did:webvh:example").unwrap(),
            "did:webvh:example"
        );
        assert_eq!(
            normalize_did_for_binding("  did:key:z6Mki  ").unwrap(),
            "did:key:z6Mki"
        );

        // Rejected: empty / whitespace-only / not a DID URI.
        assert!(normalize_did_for_binding("").is_err());
        assert!(normalize_did_for_binding("   ").is_err());
        assert!(normalize_did_for_binding("alice.example").is_err());

        // Rejected: forbidden `did:uuid:*` method (Round 4 reserves uuid).
        assert!(
            normalize_did_for_binding("did:uuid:550e8400-e29b-41d4-a716-446655440000").is_err()
        );

        // Rejected: method names with `.`/`-`/`_` (Round-4 tightens to
        // lowercase ASCII alnum only).
        assert!(normalize_did_for_binding("did:web.test:example").is_err());
        assert!(normalize_did_for_binding("did:web-test:example").is_err());
        assert!(normalize_did_for_binding("did:web_test:example").is_err());

        // Rejected: method-specific-id contains whitespace.
        assert!(normalize_did_for_binding("did:web:exa mple").is_err());
        assert!(normalize_did_for_binding("did:web:exa\tmple").is_err());

        // Rejected: missing method-specific-id segment entirely.
        assert!(normalize_did_for_binding("did:web:").is_err());
        assert!(normalize_did_for_binding("did::abc").is_err());
    }

    #[test]
    fn binding_statement_validation_accepts_exact_request_context() {
        let claims = statement_claims_default();

        validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            claims.iat,
        )
        .expect("matching statement should validate");
    }

    #[test]
    fn binding_statement_validation_rejects_nonce_replay() {
        let claims = statement_claims_default();

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "different-nonce",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            claims.iat,
        )
        .expect_err("nonce replay must reject");

        assert!(matches!(err, DidBindingProofError::NonceMismatch));
    }

    #[test]
    fn binding_statement_validation_rejects_expired_iat() {
        let claims = statement_claims_default();
        let now = claims.iat + chrono::Duration::seconds(MAX_IAT_SKEW_SECS + 1);

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            now,
        )
        .expect_err("expired statement must reject");

        assert!(matches!(err, DidBindingProofError::IatOutOfRange));
    }

    #[test]
    fn binding_statement_validation_rejects_audience_mismatch() {
        // identity-did §5.1: a proof minted for a different receiver must
        // be rejected (cross-receiver replay).
        let claims = statement_claims_default();

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            "did:web:other-receiver.example",
            TEST_TRUST_DOMAIN,
            claims.iat,
        )
        .expect_err("audience mismatch must reject");

        assert!(matches!(err, DidBindingProofError::AudienceMismatch));
    }

    #[test]
    fn binding_statement_validation_rejects_trust_domain_mismatch() {
        // identity-did §3.6: identical proof bytes carried to a different
        // deployment must trip `cross_domain_replay_rejected`.
        let claims = statement_claims_default();

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            "ak:trust_domain:other-deployment.example",
            claims.iat,
        )
        .expect_err("trust_domain mismatch must reject");

        assert!(matches!(err, DidBindingProofError::TrustDomainMismatch));
    }

    #[test]
    fn binding_statement_validation_rejects_oversized_freshness_window() {
        // identity-did §5.1: exp - iat MUST be <= 300s so an issuer can't
        // widen its own replay window.
        let mut claims = statement_claims_default();
        claims.exp = claims.iat + chrono::Duration::seconds(MAX_FRESHNESS_SECS + 1);

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            claims.iat,
        )
        .expect_err("oversized freshness window must reject");

        assert!(matches!(err, DidBindingProofError::FreshnessWindowExceeded));
    }

    #[test]
    fn binding_statement_validation_rejects_non_positive_freshness_window() {
        let mut claims = statement_claims_default();
        claims.exp = claims.iat; // exp - iat == 0

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            claims.iat,
        )
        .expect_err("non-positive freshness window must reject");

        assert!(matches!(err, DidBindingProofError::FreshnessWindowExceeded));
    }

    #[test]
    fn binding_statement_validation_rejects_after_expiry() {
        let claims = statement_claims_default();
        // now is within iat skew but at/after exp.
        let now = claims.exp;

        let err = validate_binding_statement_claims(
            &claims,
            "did:web:alice.example",
            "nonce-123",
            TEST_AUDIENCE,
            TEST_TRUST_DOMAIN,
            now,
        )
        .expect_err("expired proof must reject");

        assert!(matches!(err, DidBindingProofError::ProofExpired));
    }

    #[test]
    fn binding_nonce_is_single_use() {
        // A second submission of the same (audience, trust_domain,
        // account_did, nonce) inside the freshness window must be
        // rejected as a replay.
        let claims = statement_claims_default();
        let store = crate::services::third_party_invite::NonceStore::new();
        let key = format!(
            "{}|{}|{}|{}|{}",
            DID_BINDING_CONTROL_PROOF_SCHEMA,
            claims.audience,
            claims.trust_domain,
            claims.account_did,
            claims.nonce
        );
        store
            .check_and_record(&key, claims.exp, claims.iat)
            .expect("first use accepted");
        store
            .check_and_record(&key, claims.exp, claims.iat)
            .expect_err("replay within window rejected");
    }

    #[test]
    fn binding_statement_payload_must_be_canonical() {
        let claims = statement_claims_default();
        let canonical = canonical_json_bytes(&claims).unwrap();
        validate_canonical_statement_payload(&canonical, &claims).unwrap();

        let noncanonical = serde_json::to_vec(&claims).unwrap();
        assert_ne!(noncanonical, canonical);
        let err = validate_canonical_statement_payload(&noncanonical, &claims)
            .expect_err("non-canonical payload bytes must reject");
        assert!(matches!(
            err,
            DidBindingProofError::CanonicalStatementMismatch
        ));
    }

    #[test]
    fn compact_jws_sdk_verifier_requires_eddsa_alg() {
        let header_b64u = Base64UrlUnpadded::encode_string(
            serde_json::json!({
                "alg": "HS256",
                "kid": "did:web:alice.example#key-1",
            })
            .to_string()
            .as_bytes(),
        );
        let payload_b64u = Base64UrlUnpadded::encode_string(b"{}");
        let signature_b64u = Base64UrlUnpadded::encode_string(&[0_u8; 64]);
        let compact = format!("{header_b64u}.{payload_b64u}.{signature_b64u}");

        let err = verify_compact_jws_with_sdk(&compact, &[], "did:web:alice.example#key-1")
            .expect_err("non-EdDSA alg must reject before key lookup");

        assert!(matches!(
            err,
            SdkJwsVerifyError::UnsupportedAlgorithm(alg) if alg == "HS256"
        ));
    }

    // The fixture also carries ES256 / ML-DSA-65 vectors with a different
    // field set (they are wire-reserved, unverifiable by this Ed25519-only
    // proof path). Parse vectors loosely and select the Ed25519 one before
    // deserializing into the strongly-typed shape.
    #[derive(serde::Deserialize)]
    struct CryptoSignatureFixture {
        vectors: Vec<serde_json::Value>,
    }

    #[derive(serde::Deserialize)]
    struct CryptoSignatureVector {
        did_document_fragment: FixtureDidDocumentFragment,
        binding_object: serde_json::Value,
        canonical_binding_payload: String,
        detached_payload_b64u: String,
        proof: FixtureProof,
    }

    #[derive(serde::Deserialize)]
    struct FixtureDidDocumentFragment {
        id: String,
        #[serde(rename = "type")]
        kind: String,
        controller: String,
        #[serde(rename = "publicKeyJwk")]
        public_key_jwk: coauth_jose::jwk::PublicJsonWebKey,
    }

    #[derive(serde::Deserialize)]
    struct FixtureProof {
        verification_method: String,
        jws: String,
    }

    #[test]
    fn arkret_spec_binding_proof_fixture_verifies() {
        let fixture_path = camino::Utf8Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .join("..")
            .join("arkret-spec")
            .join("spec")
            .join("v1")
            .join("artifacts")
            .join("fixtures")
            .join("crypto-signature-fixture.json");
        let raw = match std::fs::read_to_string(&fixture_path) {
            Ok(raw) => raw,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                eprintln!(
                    "skipping arkret-spec fixture test; missing {}",
                    fixture_path.as_str()
                );
                return;
            }
            Err(error) => panic!(
                "failed reading arkret-spec fixture {}: {error}",
                fixture_path.as_str()
            ),
        };

        let fixture: CryptoSignatureFixture = serde_json::from_str(&raw).unwrap();
        let vector_value = fixture
            .vectors
            .iter()
            .find(|vector| {
                vector.get("name").and_then(serde_json::Value::as_str)
                    == Some("ak.vector.encoding.crypto.ed25519_detached_jws.v1")
            })
            .expect("expected Ed25519 detached JWS binding vector");
        let vector: CryptoSignatureVector =
            serde_json::from_value(vector_value.clone()).expect("Ed25519 vector shape");

        let canonical = canonical_json_bytes(&vector.binding_object).unwrap();
        assert_eq!(
            std::str::from_utf8(&canonical).unwrap(),
            vector.canonical_binding_payload
        );
        assert_eq!(
            Base64UrlUnpadded::encode_string(&canonical),
            vector.detached_payload_b64u
        );

        let compact = attach_detached_jws(&vector.proof.jws, &vector.detached_payload_b64u);
        let jwt: Jwt<'_, serde_json::Value> = Jwt::try_from(compact.as_str()).unwrap();
        // encoding.md §2: the detached-JWS protected header is fixed to
        // {"alg":"EdDSA"} with no kid; the verification method is carried in the
        // proof object and the signed binding, not the header.
        assert!(
            jwt.header().kid().is_none(),
            "spec-fixed Event proof header carries no kid"
        );
        let kid = vector.proof.verification_method.as_str();
        assert_eq!(kid, vector.did_document_fragment.id);
        assert_eq!(
            vector
                .binding_object
                .get("verification_method")
                .and_then(serde_json::Value::as_str),
            Some(kid)
        );

        let method = crate::handlers::arkret::VerificationMethod {
            id: vector.did_document_fragment.id.clone(),
            kind: vector.did_document_fragment.kind.clone(),
            controller: vector.did_document_fragment.controller.clone(),
            public_key_jwk: Some(vector.did_document_fragment.public_key_jwk.clone()),
            public_key_multibase: None,
        };
        // AKP-0007 P2B.3.1: verify through the SDK-mediated pure-Rust path.
        verify_compact_jws_with_sdk(&compact, std::slice::from_ref(&method), kid)
            .expect("fixture JWS should verify against DID method key");
        assert!(
            verify_compact_jws_with_sdk(
                &compact,
                std::slice::from_ref(&method),
                "did:web:alice.example#unknown",
            )
            .is_err()
        );

        let mut tampered_binding = vector.binding_object.clone();
        tampered_binding["event_digest"] =
            serde_json::Value::String(format!("sha256:{}", "0".repeat(64)));
        let tampered_payload = canonical_json_bytes(&tampered_binding).unwrap();
        assert_ne!(tampered_payload, canonical);
        let tampered_compact = attach_detached_jws(
            &vector.proof.jws,
            &Base64UrlUnpadded::encode_string(&tampered_payload),
        );
        assert!(
            verify_compact_jws_with_sdk(&tampered_compact, std::slice::from_ref(&method), kid,)
                .is_err(),
            "altered canonical binding payload must break the fixture signature"
        );
    }

    fn attach_detached_jws(detached_jws: &str, payload_b64u: &str) -> String {
        let mut parts = detached_jws.split('.');
        let protected = parts.next().expect("detached JWS header segment");
        let payload = parts.next().expect("detached JWS payload segment");
        let signature = parts.next().expect("detached JWS signature segment");
        assert!(parts.next().is_none());
        assert_eq!(payload, "");
        format!("{protected}.{payload_b64u}.{signature}")
    }
}
