[book]
title = "coauth"
authors = ["chris@sonc.ai"]
language = "en"

src = "docs/en"

[build]
build-dir = "target/book"

[output.html]
# The URL visitors will be directed to when they try to edit a page
edit-url-template = "https://github.com/cokret-dev/coauth/edit/main/{path}"

# The source code URL of the repository
git-repository-url = "https://github.com/cokret-dev/coauth"

# The path that the docs are hosted on
site-url = "/coauth/"
