apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coauth-default-deny-ingress
spec:
  podSelector:
    matchLabels:
      app: coauth
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coauth-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: coauth
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 7080
