[package]
name = "coauth"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

build = "build.rs"

[lints]
workspace = true

[dependencies]
anyhow = {workspace = true}
bytes = {workspace = true}
camino = {workspace = true}
chrono = {workspace = true}
clap = {workspace = true}
coauth-backend = {workspace = true}
coauth-config = {workspace = true}
coauth-data = {workspace = true}
coauth-messaging = {workspace = true}
coauth-tasks = {workspace = true}
console = {workspace = true}
dialoguer = {workspace = true}
dotenvy = {workspace = true}
figment = {workspace = true}
http = {workspace = true}
hyper = {workspace = true}
itertools = {workspace = true}
listenfd = {workspace = true}
opentelemetry = {workspace = true}
rand_chacha = {workspace = true}
rand_core = {workspace = true}
reqwest = {workspace = true}
rustls = {workspace = true}
salvo = {workspace = true}
sentry = {workspace = true}
sentry-tracing = {workspace = true}
serde_json = {workspace = true}
serde_yaml_ng = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
tracing-appender = {workspace = true}
tracing-opentelemetry = {workspace = true}
tracing-subscriber = {workspace = true}
url = {workspace = true}
zeroize = {workspace = true}

[features]
default = ["cedar"]

# Features used for the prebuilt binaries
dist = ["coauth-config/dist"]

# Features used in the Docker image
docker = ["coauth-config/docker"]

# Policy engine backends
cedar = ["coauth-backend/cedar"]
remote = ["coauth-backend/remote"]
password-bootstrap = ["coauth-backend/password-bootstrap"]
