[package]
name = "coauth-i18n"
description = "Internationalization support for coauth"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
arkret-locale = { workspace = true, features = ["serde"] }
camino = { workspace = true }
fluent-bundle = { workspace = true }
icu_calendar = { workspace = true }
icu_datetime = { workspace = true }
icu_experimental = { workspace = true }
icu_locid = { workspace = true }
icu_locid_transform = { workspace = true }
thiserror = { workspace = true }
unic-langid = { workspace = true }
writeable = { workspace = true }

[lints]
workspace = true
