name: Gitea Documentation Pipeline

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  CARGO_TERM_COLOR: always

concurrency:
  group: gitea-docs-${{ gitea.ref }}
  cancel-in-progress: true

jobs:
  compile-docs:
    name: Generate documentation site
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Fetch repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable

      - name: Set up mdbook
        uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2
        with:
          tool: mdbook

      - name: Generate documentation output
        run: mdbook build

      - name: Adjust file permissions
        run: chmod -R u=rwX,go=rX target/book/

      - name: Upload documentation artifact
        uses: christopherhx/gitea-upload-artifact@81f940d004763f986ba3582c007fd842dd5cb0d7 # v4 branch
        with:
          name: docs-site
          path: target/book/
