#!/usr/bin/env bash
# Generate local OIDC conformance key material.
#
# The mTLS conformance plan consumes these files from
# target/conformance-keys/ and the generated private keys must never be
# committed.

set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: conformance/conformance-keys.sh [--out-dir DIR] [--days N] [--force]

Generates local mTLS fixtures for the OpenID conformance suite:

  target/conformance-keys/mtls-client.crt
  target/conformance-keys/mtls-client.key
  target/conformance-keys/mtls-client-2.crt
  target/conformance-keys/mtls-client-2.key
  target/conformance-keys/README.md

Options:
  --out-dir DIR  Output directory. Defaults to target/conformance-keys.
  --days N       Certificate validity in days. Defaults to 365.
  --force        Overwrite existing fixture files.
  -h, --help     Show this help.
USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
out_dir="${COAUTH_CONFORMANCE_KEYS_DIR:-${repo_root}/target/conformance-keys}"
days="${COAUTH_CONFORMANCE_CERT_DAYS:-365}"
force=0

while (( $# > 0 )); do
    case "$1" in
        --out-dir)
            shift
            if [[ $# -eq 0 ]]; then
                echo "[conformance-keys] --out-dir requires a directory" >&2
                exit 2
            fi
            out_dir="$1"
            shift
            ;;
        --out-dir=*)
            out_dir="${1#--out-dir=}"
            shift
            ;;
        --days)
            shift
            if [[ $# -eq 0 ]]; then
                echo "[conformance-keys] --days requires a number" >&2
                exit 2
            fi
            days="$1"
            shift
            ;;
        --days=*)
            days="${1#--days=}"
            shift
            ;;
        --force)
            force=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[conformance-keys] unknown flag: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if ! [[ "${days}" =~ ^[1-9][0-9]*$ ]]; then
    echo "[conformance-keys] --days must be a positive integer" >&2
    exit 2
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "[conformance-keys] openssl is required to generate mTLS fixtures" >&2
    exit 2
fi

mkdir -p "${out_dir}"

refuse_existing() {
    local path="$1"
    if [[ "${force}" != "1" && -e "${path}" ]]; then
        echo "[conformance-keys] refusing to overwrite ${path}; pass --force to replace it" >&2
        exit 2
    fi
}

cert_thumbprint() {
    local cert="$1"
    openssl x509 -in "$(openssl_path "${cert}")" -outform DER \
        | openssl dgst -sha256 -binary \
        | openssl base64 -A \
        | tr '+/' '-_' \
        | tr -d '='
}

openssl_path() {
    local path="$1"
    if command -v cygpath >/dev/null 2>&1; then
        cygpath -w "${path}"
    else
        printf '%s\n' "${path}"
    fi
}

generate_client() {
    local stem="$1"
    local common_name="$2"
    local key="${out_dir}/${stem}.key"
    local cert="${out_dir}/${stem}.crt"

    refuse_existing "${key}"
    refuse_existing "${cert}"

    openssl ecparam -name prime256v1 -genkey -noout -out "$(openssl_path "${key}")"
    chmod 0600 "${key}" 2>/dev/null || true

    # Git Bash/MSYS rewrites `/CN=...` as a filesystem path unless path
    # conversion is disabled for this OpenSSL invocation. The key/cert
    # paths are already converted explicitly above.
    MSYS_NO_PATHCONV=1 openssl req -new -x509 \
        -key "$(openssl_path "${key}")" \
        -out "$(openssl_path "${cert}")" \
        -days "${days}" \
        -sha256 \
        -subj "/CN=${common_name}" \
        -addext "basicConstraints=critical,CA:FALSE" \
        -addext "keyUsage=critical,digitalSignature" \
        -addext "extendedKeyUsage=clientAuth" \
        -addext "subjectAltName=URI:urn:coauth:conformance:${stem}"

    chmod 0644 "${cert}" 2>/dev/null || true
}

generate_client "mtls-client" "coauth conformance mTLS client"
generate_client "mtls-client-2" "coauth conformance mTLS client 2"

readme="${out_dir}/README.md"
refuse_existing "${readme}"
cat > "${readme}" <<EOF
# coauth conformance key fixtures

Generated by \`conformance/conformance-keys.sh\`.

These files are local test fixtures for OpenID conformance mTLS plans.
Do not commit private keys.

| Client | Certificate | Private key | x5t#S256 |
| --- | --- | --- | --- |
| coauth-mtls-client | mtls-client.crt | mtls-client.key | $(cert_thumbprint "${out_dir}/mtls-client.crt") |
| coauth-mtls-client-2 | mtls-client-2.crt | mtls-client-2.key | $(cert_thumbprint "${out_dir}/mtls-client-2.crt") |
EOF

echo "[conformance-keys] wrote mTLS fixtures to ${out_dir}"
