apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coauth.fullname" . }}-config
  labels:
    {{- include "coauth.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.yaml | indent 4 }}
