{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coauth.serviceAccountName" . }}
  labels:
    {{- include "coauth.labels" . | nindent 4 }}
{{- end }}
