-- Squashed initial migration (coauth).
-- Final schema as of 2026-06-10, consolidated from the previous migration chain
-- (generated by applying all historical migrations and dumping the resulting schema).

CREATE FUNCTION public.handle_audit_log_block_mutation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'handle_audit_log is append-only; % is not permitted', TG_OP;
END;
$$;

CREATE TABLE public.account_claims (
    id uuid NOT NULL,
    account_id uuid,
    claim_type text NOT NULL,
    subject text NOT NULL,
    issuer text NOT NULL,
    verifier_did text NOT NULL,
    represented_org text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    revoked_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT account_claims_claim_type_non_empty CHECK ((btrim(claim_type) <> ''::text)),
    CONSTRAINT account_claims_issuer_non_empty CHECK ((btrim(issuer) <> ''::text)),
    CONSTRAINT account_claims_represented_org_non_empty CHECK ((btrim(represented_org) <> ''::text)),
    CONSTRAINT account_claims_subject_non_empty CHECK ((btrim(subject) <> ''::text)),
    CONSTRAINT account_claims_verifier_did_non_empty CHECK ((btrim(verifier_did) <> ''::text))
);

CREATE TABLE public.account_security_events (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    event_type text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.accountability_grants (
    id uuid NOT NULL,
    accountability_grant_id text NOT NULL,
    agent_id text NOT NULL,
    controller_id text NOT NULL,
    capabilities text[] NOT NULL,
    capabilities_digest text NOT NULL,
    reason text,
    issued_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revoked_reason text,
    raw_payload_digest text NOT NULL,
    soland_fanout_state text NOT NULL,
    soland_fanout_idempotency_key text NOT NULL,
    soland_fanout_payload jsonb NOT NULL,
    soland_fanout_attempt integer DEFAULT 0 NOT NULL,
    soland_fanout_next_retry_at timestamp with time zone,
    soland_fanout_dead_letter_reason text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.accountability_subject_revocations (
    id uuid NOT NULL,
    subject_kind text NOT NULL,
    subject_id text NOT NULL,
    reason text NOT NULL,
    revoked_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

-- AKP-0008 §4.5: durable accepted agent key authorizations. Column order
-- tracks event-payload.schema.json#/$defs/agent_key_authorize_payload
-- (agent_id, key_id, verification_method, accountable_principal_id,
-- audience, issued_at, expires_at) so the fan-out payload soland writes as
-- `ak.agent.key.authorize` stays field-aligned with the spec. `expires_at`
-- is NULLable: absent means the authorization never expires by time and is
-- governed solely by the revocation chain (key-management §3.6.1).
CREATE TABLE public.agent_key_authorizations (
    id uuid NOT NULL,
    authorized_event_id text NOT NULL,
    agent_id text NOT NULL,
    key_id text NOT NULL,
    verification_method text NOT NULL,
    public_key jsonb NOT NULL,
    accountable_principal_id text NOT NULL,
    agent_key_scope text NOT NULL,
    audience text[] NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    pairing_request_id text NOT NULL,
    request_canonical_digest text NOT NULL,
    revoked_at timestamp with time zone,
    revoked_reason text,
    raw_payload_digest text NOT NULL,
    soland_fanout_state text NOT NULL,
    soland_fanout_idempotency_key text NOT NULL,
    soland_fanout_payload jsonb NOT NULL,
    soland_fanout_attempt integer DEFAULT 0 NOT NULL,
    soland_fanout_next_retry_at timestamp with time zone,
    soland_fanout_dead_letter_reason text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

-- AKP-0008 §4.6: single-consumption replay table for agent_key_proof session
-- grants. Each accepted proof challenge and nonce is consumed exactly once;
-- rows survive past the proof `expires_at` by a grace window so a replay
-- inside the window is still rejected. A sweeper prunes rows past `prune_after`.
CREATE TABLE public.agent_session_proof_replay (
    id uuid NOT NULL,
    agent_id text NOT NULL,
    verification_method text NOT NULL,
    challenge text NOT NULL,
    nonce text NOT NULL,
    request_canonical_digest text NOT NULL,
    audience text NOT NULL,
    consumed_at timestamp with time zone NOT NULL,
    proof_expires_at timestamp with time zone NOT NULL,
    prune_after timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

-- RFC 9449 DPoP proof replay cache. `jti_digest` is a SHA-256 digest of
-- the caller-supplied `jti`, bounded for storage and safe for audit logs.
CREATE TABLE public.dpop_jti_replay (
    jti_digest text NOT NULL,
    seen_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.admin_operation_logs (
    id uuid NOT NULL,
    admin_user_id uuid NOT NULL,
    operation text NOT NULL,
    resource_type text NOT NULL,
    resource_id uuid,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone NOT NULL,
    audit_signature text
);

COMMENT ON COLUMN public.admin_operation_logs.audit_signature IS 'Detached signature (base64url-unpadded) over canonical JSON of the row, signed with the coauth service key. NULL during rollout.';

CREATE TABLE public.circle_capability_grants (
    id uuid NOT NULL,
    subject text NOT NULL,
    realm_id text NOT NULL,
    action text NOT NULL,
    allowed_circle_ids text[] DEFAULT '{}'::text[] NOT NULL,
    granted_by text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.organization_principal_controls (
    id uuid NOT NULL,
    organization_did text NOT NULL,
    principal_control_realm_id text NOT NULL,
    control_stream_ref text,
    pcr_frontier_digest text,
    bootstrap_authorization text NOT NULL,
    bootstrap_delegation_ref text,
    executed_by text,
    bootstrap_proof_digest text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

COMMENT ON TABLE public.organization_principal_controls IS 'Organization principal control state (identity-did.md §7). One row per organization DID. There is intentionally no shared-credential/password column: an organization principal is controlled by DID keys + delegations only, never a shared human login.';

CREATE TABLE public.organization_delegations (
    id uuid NOT NULL,
    delegation_ref text NOT NULL,
    organization_did text NOT NULL,
    delegate_did text NOT NULL,
    issuer_role text NOT NULL,
    purposes text[] DEFAULT '{}'::text[] NOT NULL,
    covered_relationships text[] DEFAULT '{}'::text[] NOT NULL,
    covered_control_scopes text[] DEFAULT '{}'::text[] NOT NULL,
    status text NOT NULL,
    valid_from timestamp with time zone NOT NULL,
    valid_until timestamp with time zone,
    created_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone
);

COMMENT ON TABLE public.organization_delegations IS 'Organization DID delegations to Account Authority / governance service principals. Backs the SDK RealmOrganizationDelegationResolver and the ak.realm.organization issuance + audit API.';

CREATE TABLE public.collaboration_capability_grants (
    id uuid NOT NULL,
    capability_grant_id text NOT NULL,
    grant_event_id text NOT NULL,
    revoke_event_id text,
    subject text NOT NULL,
    realm_id text NOT NULL,
    action text NOT NULL,
    expires_at timestamp with time zone,
    approval_evidence_ref text,
    granted_by text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    grant_raw_payload_digest text NOT NULL,
    grant_fanout_idempotency_key text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.handle_audit_log (
    id uuid NOT NULL,
    user_id uuid,
    event_type text NOT NULL,
    handle text,
    handle_aliases text[] DEFAULT ARRAY[]::text[] NOT NULL,
    old_did text,
    new_did text,
    issuer_service_id text,
    audience text,
    claim_digest text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    actor_id uuid,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.invite_quarantine_queue (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peer_did text NOT NULL,
    target_holder_did text NOT NULL,
    consent_id text NOT NULL,
    scope text NOT NULL,
    requesting_admin_did text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    resolved_at timestamp with time zone,
    resolution_note text,
    CONSTRAINT invite_quarantine_queue_consent_id_non_empty CHECK ((btrim(consent_id) <> ''::text)),
    CONSTRAINT invite_quarantine_queue_peer_did_non_empty CHECK ((btrim(peer_did) <> ''::text)),
    CONSTRAINT invite_quarantine_queue_scope_non_empty CHECK ((btrim(scope) <> ''::text)),
    CONSTRAINT invite_quarantine_queue_status_known CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))),
    CONSTRAINT invite_quarantine_queue_target_holder_did_non_empty CHECK ((btrim(target_holder_did) <> ''::text))
);

CREATE TABLE public.notification_deliveries (
    id uuid NOT NULL,
    notification_request_id uuid NOT NULL,
    channel text NOT NULL,
    destination jsonb NOT NULL,
    provider_binding_key text,
    provider_message_id text,
    attempt_count integer NOT NULL,
    status text NOT NULL,
    last_failure jsonb,
    created_at timestamp with time zone NOT NULL,
    reserved_at timestamp with time zone,
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    failed_at timestamp with time zone,
    next_retry_at timestamp with time zone
);

CREATE TABLE public.notification_event_logs (
    id uuid NOT NULL,
    notification_request_id uuid NOT NULL,
    notification_delivery_id uuid,
    kind text NOT NULL,
    actor jsonb NOT NULL,
    summary text,
    metadata jsonb NOT NULL,
    occurred_at timestamp with time zone NOT NULL
);

CREATE TABLE public.notification_preferences (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    channel text NOT NULL,
    enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.notification_requests (
    id uuid NOT NULL,
    template_key text NOT NULL,
    locale text NOT NULL,
    source jsonb NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL,
    dedupe_key text,
    correlation_key text,
    created_at timestamp with time zone NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone
);

CREATE TABLE public.notification_template_versions (
    id uuid NOT NULL,
    template_key text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    channel text NOT NULL,
    locale text DEFAULT 'en'::text NOT NULL,
    subject_template text,
    body_template text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    published_at timestamp with time zone
);

CREATE TABLE public.oauth_access_tokens (
    id uuid NOT NULL,
    oauth_session_id uuid NOT NULL,
    access_token text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    first_used_at timestamp with time zone
);

CREATE TABLE public.oauth_authorization_grants (
    id uuid NOT NULL,
    oauth_client_id uuid NOT NULL,
    oauth_session_id uuid,
    authorization_code text,
    redirect_uri text NOT NULL,
    scope text NOT NULL,
    state text,
    nonce text,
    response_mode text DEFAULT 'query'::text NOT NULL,
    code_challenge_method text,
    code_challenge text,
    response_type_code boolean NOT NULL,
    response_type_id_token boolean NOT NULL,
    requires_consent boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone NOT NULL,
    fulfilled_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    exchanged_at timestamp with time zone,
    login_hint text,
    locale text
);

CREATE TABLE public.oauth_client_localized_metadata (
    client_id uuid NOT NULL,
    locale text NOT NULL,
    field text NOT NULL,
    value text NOT NULL,
    CONSTRAINT oauth_client_localized_metadata_field_check CHECK ((field = ANY (ARRAY['client_name'::text, 'logo_uri'::text, 'client_uri'::text, 'policy_uri'::text, 'tos_uri'::text])))
);

CREATE TABLE public.oauth_clients (
    id uuid NOT NULL,
    encrypted_client_secret text,
    grant_type_authorization_code boolean NOT NULL,
    grant_type_refresh_token boolean NOT NULL,
    grant_type_client_credentials boolean DEFAULT false NOT NULL,
    grant_type_device_code boolean,
    client_name text,
    logo_uri text,
    client_uri text,
    policy_uri text,
    tos_uri text,
    jwks_uri text,
    jwks jsonb,
    id_token_signed_response_alg text,
    token_endpoint_auth_method text,
    token_endpoint_auth_signing_alg text,
    initiate_login_uri text,
    userinfo_signed_response_alg text,
    redirect_uris text[] DEFAULT '{}'::text[] NOT NULL,
    application_type text,
    contacts text[] DEFAULT '{}'::text[] NOT NULL,
    is_static boolean,
    created_at timestamp with time zone,
    metadata_digest text,
    i18n jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE TABLE public.oauth_device_code_grant (
    id uuid NOT NULL,
    oauth_client_id uuid NOT NULL,
    scope text NOT NULL,
    user_code text NOT NULL,
    device_code text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    fulfilled_at timestamp with time zone,
    rejected_at timestamp with time zone,
    exchanged_at timestamp with time zone,
    oauth_session_id uuid,
    user_session_id uuid,
    ip_address inet,
    user_agent text
);

CREATE TABLE public.oauth_refresh_tokens (
    id uuid NOT NULL,
    oauth_session_id uuid NOT NULL,
    oauth_access_token_id uuid,
    refresh_token text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    revoked_at timestamp with time zone,
    next_oauth_refresh_token_id uuid,
    chain_root_oauth_refresh_token_id uuid NOT NULL,
    chain_created_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);

CREATE TABLE public.oauth_session_grants (
    id uuid NOT NULL,
    grant_id uuid NOT NULL,
    user_session_id uuid,
    issuer text NOT NULL,
    subject text NOT NULL,
    device_id text,
    applet_id text,
    effective_scope jsonb,
    registration_epoch text,
    service_id text,
    capability_grant_refs text[] DEFAULT '{}'::text[] NOT NULL,
    audience text NOT NULL,
    scope_list text[] NOT NULL,
    grant_jwt text NOT NULL,
    session_public_key text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone
);

CREATE TABLE public.oauth_sessions (
    id uuid NOT NULL,
    user_session_id uuid,
    oauth_client_id uuid NOT NULL,
    user_id uuid NOT NULL,
    scope_list text[] NOT NULL,
    created_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    user_agent text,
    last_active_at timestamp with time zone,
    last_active_ip inet,
    human_name text
);

CREATE TABLE public.personal_access_tokens (
    id uuid NOT NULL,
    personal_session_id uuid NOT NULL,
    access_token_sha256 bytea NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT personal_access_tokens_access_token_sha256_check CHECK ((length(access_token_sha256) = 32))
);

CREATE TABLE public.personal_sessions (
    id uuid NOT NULL,
    owner_user_id uuid,
    owner_oauth_client_id uuid,
    actor_user_id uuid NOT NULL,
    human_name text NOT NULL,
    scope_list text[] NOT NULL,
    created_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_active_at timestamp with time zone,
    last_active_ip inet
);

CREATE TABLE public.policy_data (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    data jsonb NOT NULL
);

CREATE TABLE public.principal_did_owners (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    principal_id text NOT NULL,
    key_log_head text NOT NULL,
    enrollment_authority_did text NOT NULL,
    enrollment_authority_ref text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.principal_did_bindings (
    id uuid NOT NULL,
    principal_did_owner_id uuid NOT NULL,
    user_id uuid NOT NULL,
    audience text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.account_handoff_grants (
    id uuid NOT NULL,
    request_id uuid NOT NULL,
    request_digest text NOT NULL,
    service_account_id uuid NOT NULL,
    browser_session_id uuid,
    audience text NOT NULL,
    cnf_jkt text NOT NULL,
    allowed_operations text[] NOT NULL,
    account_handoff_grant text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    consumed_at timestamp with time zone,
    CONSTRAINT account_handoff_grants_request_digest_valid CHECK ((request_digest ~ '^sha256:[0-9a-f]{64}$'::text)),
    CONSTRAINT account_handoff_grants_audience_nonempty CHECK ((btrim(audience) <> ''::text)),
    CONSTRAINT account_handoff_grants_cnf_jkt_valid CHECK ((cnf_jkt ~ '^[A-Za-z0-9_-]{43}$'::text)),
    CONSTRAINT account_handoff_grants_allowed_operations_closed CHECK ((allowed_operations = ARRAY['ak.gate.account.command.issue_identity_binding_challenge'::text, 'ak.gate.account.command.register'::text, 'ak.gate.account.command.issue_session_grant'::text])),
    CONSTRAINT account_handoff_grants_token_nonempty CHECK ((length(account_handoff_grant) >= 32)),
    CONSTRAINT account_handoff_grants_expiry_valid CHECK ((expires_at > issued_at))
);

CREATE TABLE public.identity_creation_leases (
    service_account_id uuid NOT NULL,
    audience text NOT NULL,
    lease_id text NOT NULL,
    holder_jkt text NOT NULL,
    fence bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    reserved_principal_id text,
    reserved_operation_digest text,
    did_operation jsonb,
    state text NOT NULL,
    registry_receipt jsonb,
    head_event_digest text,
    binding_receipt jsonb,
    first_device_id text,
    first_device_enrolled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT identity_creation_leases_audience_nonempty CHECK ((btrim(audience) <> ''::text)),
    CONSTRAINT identity_creation_leases_lease_id_valid CHECK ((lease_id ~ '^[A-Za-z0-9_-]{22,128}$'::text)),
    CONSTRAINT identity_creation_leases_holder_jkt_valid CHECK ((holder_jkt ~ '^[A-Za-z0-9_-]{43}$'::text)),
    CONSTRAINT identity_creation_leases_fence_positive CHECK ((fence >= 1)),
    CONSTRAINT identity_creation_leases_operation_digest_valid CHECK (((reserved_operation_digest IS NULL) OR (reserved_operation_digest ~ '^sha256:[0-9a-f]{64}$'::text))),
    CONSTRAINT identity_creation_leases_head_digest_valid CHECK (((head_event_digest IS NULL) OR (head_event_digest ~ '^sha256:[0-9a-f]{64}$'::text))),
    CONSTRAINT identity_creation_leases_state_valid CHECK ((state = ANY (ARRAY['active'::text, 'reserved'::text, 'published'::text, 'bound'::text]))),
    CONSTRAINT identity_creation_leases_reservation_complete CHECK ((((reserved_principal_id IS NULL) AND (reserved_operation_digest IS NULL) AND (did_operation IS NULL)) OR ((reserved_principal_id IS NOT NULL) AND (reserved_operation_digest IS NOT NULL) AND (did_operation IS NOT NULL)))),
    CONSTRAINT identity_creation_leases_first_device_complete CHECK ((((first_device_id IS NULL) AND (first_device_enrolled_at IS NULL)) OR ((first_device_id IS NOT NULL) AND (first_device_enrolled_at IS NOT NULL))))
);

CREATE TABLE public.identity_binding_challenges (
    request_id uuid NOT NULL,
    request_digest text NOT NULL,
    service_account_id uuid NOT NULL,
    challenge_id text NOT NULL,
    challenge text NOT NULL,
    purpose text NOT NULL,
    principal_id text NOT NULL,
    operation_digest text NOT NULL,
    lease_id text NOT NULL,
    lease_fence bigint NOT NULL,
    dpop_jkt text NOT NULL,
    audience text NOT NULL,
    origin text NOT NULL,
    trust_domain text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    replaced_at timestamp with time zone,
    CONSTRAINT identity_binding_challenges_request_digest_valid CHECK ((request_digest ~ '^sha256:[0-9a-f]{64}$'::text)),
    CONSTRAINT identity_binding_challenges_challenge_id_valid CHECK ((challenge_id ~ '^[A-Za-z0-9_-]{22,128}$'::text)),
    CONSTRAINT identity_binding_challenges_challenge_nonempty CHECK ((length(challenge) >= 22)),
    CONSTRAINT identity_binding_challenges_purpose_valid CHECK ((purpose = 'account_binding'::text)),
    CONSTRAINT identity_binding_challenges_operation_digest_valid CHECK ((operation_digest ~ '^sha256:[0-9a-f]{64}$'::text)),
    CONSTRAINT identity_binding_challenges_lease_id_valid CHECK ((lease_id ~ '^[A-Za-z0-9_-]{22,128}$'::text)),
    CONSTRAINT identity_binding_challenges_lease_fence_positive CHECK ((lease_fence >= 1)),
    CONSTRAINT identity_binding_challenges_dpop_jkt_valid CHECK ((dpop_jkt ~ '^[A-Za-z0-9_-]{43}$'::text)),
    CONSTRAINT identity_binding_challenges_expiry_valid CHECK ((expires_at > issued_at AND expires_at <= (issued_at + '00:05:00'::interval)))
);

CREATE TABLE public.queue_jobs (
    id uuid NOT NULL,
    status text DEFAULT 'available'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    started_by uuid,
    completed_at timestamp with time zone,
    queue_name text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    failed_at timestamp with time zone,
    failed_reason text,
    attempt integer DEFAULT 0 NOT NULL,
    next_attempt_id uuid,
    scheduled_at timestamp with time zone,
    schedule_name text
);

CREATE UNLOGGED TABLE public.queue_leader (
    active boolean DEFAULT true NOT NULL,
    elected_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    queue_worker_id uuid NOT NULL
);

CREATE TABLE public.queue_schedules (
    schedule_name text NOT NULL,
    last_scheduled_at timestamp with time zone,
    last_scheduled_job_id uuid
);

CREATE TABLE public.queue_workers (
    id uuid NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    shutdown_at timestamp with time zone
);

CREATE TABLE public.risk_action_proposals (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    action text NOT NULL,
    proposer_did text NOT NULL,
    reason text NOT NULL,
    ticket text,
    state text DEFAULT 'draft'::text NOT NULL,
    approval_proofs jsonb DEFAULT '[]'::jsonb NOT NULL,
    required_approvals integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    approved_at timestamp with time zone,
    executed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    CONSTRAINT risk_action_proposals_action_non_empty CHECK ((btrim(action) <> ''::text)),
    CONSTRAINT risk_action_proposals_proposer_did_non_empty CHECK ((btrim(proposer_did) <> ''::text)),
    CONSTRAINT risk_action_proposals_reason_non_empty CHECK ((btrim(reason) <> ''::text)),
    CONSTRAINT risk_action_proposals_required_approvals_positive CHECK ((required_approvals >= 1)),
    CONSTRAINT risk_action_proposals_state_valid CHECK ((state = ANY (ARRAY['draft'::text, 'approved'::text, 'executed'::text, 'cancelled'::text, 'rejected'::text])))
);

CREATE TABLE public.service_identity (
    id smallint PRIMARY KEY,
    identity jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT service_identity_singleton CHECK ((id = 1))
);

CREATE TABLE public.upstream_oauth_authorization_sessions (
    id uuid NOT NULL,
    upstream_oauth_provider_id uuid CONSTRAINT upstream_oauth_authorizatio_upstream_oauth_provider_id_not_null NOT NULL,
    upstream_oauth_link_id uuid,
    id_token text,
    state text NOT NULL,
    code_challenge_verifier text,
    nonce text,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    consumed_at timestamp with time zone,
    id_token_claims jsonb,
    userinfo jsonb,
    extra_callback_parameters jsonb,
    unlinked_at timestamp with time zone,
    user_session_id uuid
);

CREATE TABLE public.upstream_oauth_links (
    id uuid NOT NULL,
    upstream_oauth_provider_id uuid NOT NULL,
    user_id uuid,
    subject text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    human_account_name text,
    unlinked_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.upstream_oauth_providers (
    id uuid NOT NULL,
    issuer text,
    scope text NOT NULL,
    client_id text NOT NULL,
    encrypted_client_secret text,
    token_endpoint_signing_alg text,
    token_endpoint_auth_method text NOT NULL,
    jwks_uri_override text,
    authorization_endpoint_override text,
    token_endpoint_override text,
    discovery_mode text DEFAULT 'oidc'::text NOT NULL,
    pkce_mode text DEFAULT 'auto'::text NOT NULL,
    human_name text,
    brand_name text,
    created_at timestamp with time zone NOT NULL,
    claims_imports jsonb,
    disabled_at timestamp with time zone,
    additional_parameters jsonb,
    fetch_userinfo boolean DEFAULT false NOT NULL,
    userinfo_endpoint_override text,
    response_mode text,
    extra_callback_parameters jsonb,
    ui_order integer DEFAULT 0 NOT NULL,
    id_token_signed_response_alg text DEFAULT 'RS256'::text NOT NULL,
    userinfo_signed_response_alg text,
    on_backchannel_logout text,
    forward_login_hint boolean DEFAULT false NOT NULL,
    source text DEFAULT 'config'::text NOT NULL
);

CREATE TABLE public.user_email_authentication_codes (
    id uuid NOT NULL,
    user_email_authentication_id uuid CONSTRAINT user_email_authentication_c_user_email_authentication__not_null NOT NULL,
    code text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_email_authentications (
    id uuid NOT NULL,
    user_session_id uuid,
    user_registration_id uuid,
    email text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.user_emails (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    confirmed_at timestamp with time zone,
    is_primary boolean DEFAULT false NOT NULL
);

CREATE TABLE public.user_passwords (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    hashed_password text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    version integer NOT NULL,
    upgraded_from_id uuid
);

CREATE TABLE public.user_phone_authentication_codes (
    id uuid NOT NULL,
    user_phone_authentication_id uuid CONSTRAINT user_phone_authentication_c_user_phone_authentication__not_null NOT NULL,
    code text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_phone_authentications (
    id uuid NOT NULL,
    user_registration_id uuid,
    phone text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.user_phones (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    phone text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_primary_handle_preferences (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    handle text,
    effective_at timestamp with time zone NOT NULL,
    replaced_at timestamp with time zone,
    source_claim_id uuid,
    source_claim_digest text,
    actor_user_id uuid,
    source text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT user_primary_handle_preferences_check CHECK (((replaced_at IS NULL) OR (replaced_at > effective_at))),
    CONSTRAINT user_primary_handle_preferences_check1 CHECK (((handle IS NULL) OR ((source_claim_id IS NOT NULL) AND (source_claim_digest IS NOT NULL)))),
    CONSTRAINT user_primary_handle_preferences_handle_check CHECK (((handle IS NULL) OR ((POSITION((':'::text) IN (handle)) > 1) AND (handle = lower(handle)) AND (handle !~~ 'acct:%'::text) AND (handle !~~ 'arkret://%'::text))))
);

CREATE TABLE public.user_recovery_sessions (
    id uuid NOT NULL,
    email text NOT NULL,
    user_agent text NOT NULL,
    ip_address inet,
    locale text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE public.user_recovery_tickets (
    id uuid NOT NULL,
    user_recovery_session_id uuid NOT NULL,
    user_email_id uuid NOT NULL,
    ticket text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_registration_tokens (
    id uuid NOT NULL,
    token text NOT NULL,
    usage_limit integer,
    times_used integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone
);

CREATE TABLE public.user_registrations (
    id uuid NOT NULL,
    ip_address inet,
    user_agent text,
    post_auth_action jsonb,
    localpart text NOT NULL,
    display_name text,
    avatar_url text,
    terms_url text,
    email_authentication_id uuid,
    hashed_password text,
    hashed_password_version integer,
    user_registration_token_id uuid,
    upstream_oauth_authorization_session_id uuid,
    phone_authentication_id uuid,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.user_session_authentications (
    id uuid NOT NULL,
    user_session_id uuid NOT NULL,
    user_password_id uuid,
    upstream_oauth_authorization_session_id uuid,
    created_at timestamp with time zone NOT NULL,
    authentication_source text
);

CREATE TABLE public.user_sessions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    user_agent text,
    last_active_at timestamp with time zone,
    last_active_ip inet
);

CREATE TABLE public.user_terms (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    terms_url text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_totp_configs (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    secret text NOT NULL,
    algorithm text DEFAULT 'SHA1'::text NOT NULL,
    digits integer DEFAULT 6 NOT NULL,
    period integer DEFAULT 30 NOT NULL,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.user_unsupported_third_party_ids (
    user_id uuid NOT NULL,
    medium text NOT NULL,
    address text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.users (
    id uuid NOT NULL,
    localpart text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'active'::text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'soft_logged_out'::text, 'locked'::text, 'suspended'::text, 'deactivated'::text, 'erasure_pending'::text])),
    locked_at timestamp with time zone,
    deactivated_at timestamp with time zone,
    can_request_admin boolean DEFAULT false NOT NULL,
    is_guest boolean DEFAULT false NOT NULL,
    display_name text,
    avatar_url text,
    preferred_locale text,
    handle_aliases text[] DEFAULT ARRAY[]::text[] NOT NULL
);

CREATE TABLE public.webauthn_credentials (
    id uuid NOT NULL,
    account_id uuid NOT NULL,
    credential_id bytea NOT NULL,
    public_key jsonb NOT NULL,
    sign_count bigint DEFAULT 0 NOT NULL,
    transports text[] DEFAULT ARRAY[]::text[] NOT NULL,
    aaguid uuid,
    backup_eligible boolean DEFAULT false NOT NULL,
    backup_state boolean DEFAULT false NOT NULL,
    user_verified boolean DEFAULT false NOT NULL,
    label text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone
);

CREATE TABLE public.workflow_audit_logs (
    id uuid NOT NULL,
    workflow_instance_id uuid NOT NULL,
    workflow_step_id uuid,
    action text NOT NULL,
    actor jsonb NOT NULL,
    summary text,
    metadata jsonb NOT NULL,
    occurred_at timestamp with time zone NOT NULL
);

CREATE TABLE public.workflow_deadlines (
    id uuid NOT NULL,
    workflow_instance_id uuid NOT NULL,
    workflow_step_id uuid,
    deadline_key text NOT NULL,
    status text NOT NULL,
    payload jsonb NOT NULL,
    due_at timestamp with time zone NOT NULL,
    satisfied_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.workflow_events (
    id uuid NOT NULL,
    workflow_instance_id uuid NOT NULL,
    workflow_step_id uuid,
    kind text NOT NULL,
    actor jsonb NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamp with time zone NOT NULL
);

CREATE TABLE public.workflow_instances (
    id uuid NOT NULL,
    workflow_key text NOT NULL,
    subject jsonb NOT NULL,
    trigger jsonb NOT NULL,
    status text NOT NULL,
    current_step_key text,
    input jsonb NOT NULL,
    context jsonb DEFAULT '{}'::jsonb NOT NULL,
    correlation_key text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    expires_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE public.workflow_steps (
    id uuid NOT NULL,
    workflow_instance_id uuid NOT NULL,
    step_key text NOT NULL,
    sequence integer NOT NULL,
    status text NOT NULL,
    assignee jsonb,
    input jsonb NOT NULL,
    output jsonb,
    attempt_count integer NOT NULL,
    last_error_code text,
    last_error_message text,
    scheduled_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY public.account_claims
    ADD CONSTRAINT account_claims_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_security_events
    ADD CONSTRAINT account_security_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accountability_grants
    ADD CONSTRAINT accountability_grants_accountability_grant_id_key UNIQUE (accountability_grant_id);

ALTER TABLE ONLY public.accountability_grants
    ADD CONSTRAINT accountability_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accountability_grants
    ADD CONSTRAINT accountability_grants_soland_fanout_idempotency_key_key UNIQUE (soland_fanout_idempotency_key);

ALTER TABLE ONLY public.accountability_subject_revocations
    ADD CONSTRAINT accountability_subject_revocations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accountability_subject_revocations
    ADD CONSTRAINT accountability_subject_revocations_subject_kind_subject_id_key UNIQUE (subject_kind, subject_id);

ALTER TABLE ONLY public.agent_key_authorizations
    ADD CONSTRAINT agent_key_authorizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_key_authorizations
    ADD CONSTRAINT agent_key_authorizations_authorized_event_id_key UNIQUE (authorized_event_id);

ALTER TABLE ONLY public.agent_key_authorizations
    ADD CONSTRAINT agent_key_authorizations_soland_fanout_idempotency_key_key UNIQUE (soland_fanout_idempotency_key);

ALTER TABLE ONLY public.agent_session_proof_replay
    ADD CONSTRAINT agent_session_proof_replay_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.agent_session_proof_replay
    ADD CONSTRAINT agent_session_proof_replay_challenge_key UNIQUE (agent_id, verification_method, challenge);

ALTER TABLE ONLY public.agent_session_proof_replay
    ADD CONSTRAINT agent_session_proof_replay_nonce_key UNIQUE (agent_id, verification_method, nonce);

ALTER TABLE ONLY public.dpop_jti_replay
    ADD CONSTRAINT dpop_jti_replay_pkey PRIMARY KEY (jti_digest);

ALTER TABLE ONLY public.admin_operation_logs
    ADD CONSTRAINT admin_operation_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.circle_capability_grants
    ADD CONSTRAINT circle_capability_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organization_principal_controls
    ADD CONSTRAINT organization_principal_controls_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organization_delegations
    ADD CONSTRAINT organization_delegations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.collaboration_capability_grants
    ADD CONSTRAINT collaboration_capability_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.handle_audit_log
    ADD CONSTRAINT handle_audit_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invite_quarantine_queue
    ADD CONSTRAINT invite_quarantine_queue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_event_logs
    ADD CONSTRAINT notification_event_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_requests
    ADD CONSTRAINT notification_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_template_versions
    ADD CONSTRAINT notification_template_versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_access_token_key UNIQUE (access_token);

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_authorization_grants
    ADD CONSTRAINT oauth_authorization_grants_authorization_code_key UNIQUE (authorization_code);

ALTER TABLE ONLY public.oauth_authorization_grants
    ADD CONSTRAINT oauth_authorization_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_client_localized_metadata
    ADD CONSTRAINT oauth_client_localized_metadata_pkey PRIMARY KEY (client_id, locale, field);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_metadata_digest_key UNIQUE (metadata_digest);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_device_code_key UNIQUE (device_code);

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_user_code_key UNIQUE (user_code);

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_refresh_token_key UNIQUE (refresh_token);

ALTER TABLE ONLY public.oauth_session_grants
    ADD CONSTRAINT oauth_session_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_sessions
    ADD CONSTRAINT oauth_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_access_token_sha256_key UNIQUE (access_token_sha256);

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.personal_sessions
    ADD CONSTRAINT personal_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.policy_data
    ADD CONSTRAINT policy_data_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.principal_did_bindings
    ADD CONSTRAINT principal_did_bindings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.principal_did_bindings
    ADD CONSTRAINT principal_did_bindings_owner_audience_unique UNIQUE (principal_did_owner_id, audience);

ALTER TABLE ONLY public.principal_did_bindings
    ADD CONSTRAINT principal_did_bindings_user_audience_unique UNIQUE (user_id, audience);

ALTER TABLE ONLY public.principal_did_bindings
    ADD CONSTRAINT principal_did_bindings_audience_nonempty CHECK (btrim(audience) <> '');

ALTER TABLE ONLY public.principal_did_owners
    ADD CONSTRAINT principal_did_owners_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.principal_did_owners
    ADD CONSTRAINT principal_did_owners_id_user_unique UNIQUE (id, user_id);

ALTER TABLE ONLY public.principal_did_owners
    ADD CONSTRAINT principal_did_owners_principal_id_unique UNIQUE (principal_id);

ALTER TABLE ONLY public.principal_did_owners
    ADD CONSTRAINT principal_did_owners_fields_nonempty CHECK (
        btrim(principal_id) <> '' AND
        btrim(key_log_head) <> '' AND
        btrim(enrollment_authority_did) <> '' AND
        left(enrollment_authority_ref, length(principal_id) + 1) = principal_id || '#' AND
        length(enrollment_authority_ref) > length(principal_id) + 1
    );

ALTER TABLE ONLY public.account_handoff_grants
    ADD CONSTRAINT account_handoff_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_handoff_grants
    ADD CONSTRAINT account_handoff_grants_request_id_unique UNIQUE (request_id);

ALTER TABLE ONLY public.account_handoff_grants
    ADD CONSTRAINT account_handoff_grants_token_unique UNIQUE (account_handoff_grant);

ALTER TABLE ONLY public.identity_creation_leases
    ADD CONSTRAINT identity_creation_leases_pkey PRIMARY KEY (service_account_id, audience);

ALTER TABLE ONLY public.identity_creation_leases
    ADD CONSTRAINT identity_creation_leases_lease_id_unique UNIQUE (lease_id);

ALTER TABLE ONLY public.identity_binding_challenges
    ADD CONSTRAINT identity_binding_challenges_pkey PRIMARY KEY (request_id);

ALTER TABLE ONLY public.identity_binding_challenges
    ADD CONSTRAINT identity_binding_challenges_challenge_id_unique UNIQUE (challenge_id);

ALTER TABLE ONLY public.queue_jobs
    ADD CONSTRAINT queue_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.queue_leader
    ADD CONSTRAINT queue_leader_active_key UNIQUE (active);

ALTER TABLE ONLY public.queue_schedules
    ADD CONSTRAINT queue_schedules_pkey PRIMARY KEY (schedule_name);

ALTER TABLE ONLY public.queue_workers
    ADD CONSTRAINT queue_workers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.risk_action_proposals
    ADD CONSTRAINT risk_action_proposals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.upstream_oauth_authorization_sessions
    ADD CONSTRAINT upstream_oauth_authorization_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.upstream_oauth_authorization_sessions
    ADD CONSTRAINT upstream_oauth_authorization_sessions_state_key UNIQUE (state);

ALTER TABLE ONLY public.upstream_oauth_links
    ADD CONSTRAINT upstream_oauth_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.upstream_oauth_links
    ADD CONSTRAINT upstream_oauth_links_upstream_oauth_provider_id_subject_key UNIQUE (upstream_oauth_provider_id, subject);

ALTER TABLE ONLY public.upstream_oauth_providers
    ADD CONSTRAINT upstream_oauth_providers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_email_authentication_codes
    ADD CONSTRAINT user_email_authentication_cod_user_email_authentication_id__key UNIQUE (user_email_authentication_id, code);

ALTER TABLE ONLY public.user_email_authentication_codes
    ADD CONSTRAINT user_email_authentication_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_email_authentications
    ADD CONSTRAINT user_email_authentications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_emails
    ADD CONSTRAINT user_emails_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_passwords
    ADD CONSTRAINT user_passwords_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_phone_authentication_codes
    ADD CONSTRAINT user_phone_authentication_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_phone_authentications
    ADD CONSTRAINT user_phone_authentications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_phones
    ADD CONSTRAINT user_phones_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_primary_handle_preferences
    ADD CONSTRAINT user_primary_handle_preferences_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_recovery_sessions
    ADD CONSTRAINT user_recovery_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_recovery_tickets
    ADD CONSTRAINT user_recovery_tickets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_registration_tokens
    ADD CONSTRAINT user_registration_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_registration_tokens
    ADD CONSTRAINT user_registration_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.user_registrations
    ADD CONSTRAINT user_registrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_session_authentications
    ADD CONSTRAINT user_session_authentications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_terms
    ADD CONSTRAINT user_terms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_terms
    ADD CONSTRAINT user_terms_user_id_terms_url_key UNIQUE (user_id, terms_url);

ALTER TABLE ONLY public.user_totp_configs
    ADD CONSTRAINT user_totp_configs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_totp_configs
    ADD CONSTRAINT user_totp_configs_user_id_unique UNIQUE (user_id);

ALTER TABLE ONLY public.user_unsupported_third_party_ids
    ADD CONSTRAINT user_unsupported_third_party_ids_pkey PRIMARY KEY (user_id, medium, address);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_localpart_key UNIQUE (localpart);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webauthn_credentials
    ADD CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_audit_logs
    ADD CONSTRAINT workflow_audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_deadlines
    ADD CONSTRAINT workflow_deadlines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_events
    ADD CONSTRAINT workflow_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_instances
    ADD CONSTRAINT workflow_instances_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_steps
    ADD CONSTRAINT workflow_steps_pkey PRIMARY KEY (id);

CREATE INDEX account_claims_account_id_issued_idx ON public.account_claims USING btree (account_id, issued_at DESC) WHERE (account_id IS NOT NULL);

CREATE INDEX account_claims_lifecycle_idx ON public.account_claims USING btree (revoked_at, expires_at);

CREATE INDEX account_claims_represented_org_idx ON public.account_claims USING btree (represented_org);

CREATE INDEX account_claims_subject_idx ON public.account_claims USING btree (subject);

CREATE INDEX account_claims_verifier_did_idx ON public.account_claims USING btree (verifier_did);

CREATE INDEX account_security_events_type_created_idx ON public.account_security_events USING btree (event_type, created_at);

CREATE INDEX account_security_events_user_created_idx ON public.account_security_events USING btree (user_id, created_at);

CREATE UNIQUE INDEX accountability_grants_active_fingerprint_idx ON public.accountability_grants USING btree (agent_id, controller_id, capabilities_digest) WHERE (revoked_at IS NULL);

CREATE INDEX accountability_grants_agent_active_idx ON public.accountability_grants USING btree (agent_id, issued_at) WHERE (revoked_at IS NULL);

CREATE INDEX accountability_grants_controller_active_idx ON public.accountability_grants USING btree (controller_id, issued_at) WHERE (revoked_at IS NULL);

CREATE INDEX accountability_grants_revoked_idx ON public.accountability_grants USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);

CREATE INDEX accountability_subject_revocations_subject_idx ON public.accountability_subject_revocations USING btree (subject_kind, subject_id, revoked_at);

CREATE INDEX agent_key_authorizations_agent_active_idx ON public.agent_key_authorizations USING btree (agent_id, issued_at) WHERE (revoked_at IS NULL);

CREATE INDEX agent_key_authorizations_revoked_idx ON public.agent_key_authorizations USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);

CREATE INDEX agent_session_proof_replay_prune_idx ON public.agent_session_proof_replay USING btree (prune_after);

CREATE INDEX dpop_jti_replay_expires_at_idx ON public.dpop_jti_replay USING btree (expires_at);

CREATE INDEX admin_operation_logs_created_idx ON public.admin_operation_logs USING btree (created_at);

CREATE INDEX admin_operation_logs_resource_idx ON public.admin_operation_logs USING btree (resource_type, resource_id) WHERE (resource_id IS NOT NULL);

CREATE INDEX admin_operation_logs_user_created_idx ON public.admin_operation_logs USING btree (admin_user_id, created_at);

CREATE UNIQUE INDEX circle_capability_grants_active_fingerprint_idx ON public.circle_capability_grants USING btree (subject, realm_id, action, allowed_circle_ids) WHERE (revoked_at IS NULL);

CREATE INDEX circle_capability_grants_active_realm_subject_idx ON public.circle_capability_grants USING btree (realm_id, subject, granted_at) WHERE (revoked_at IS NULL);

CREATE INDEX circle_capability_grants_revoked_idx ON public.circle_capability_grants USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);

CREATE UNIQUE INDEX organization_principal_controls_org_did_idx ON public.organization_principal_controls USING btree (organization_did);

CREATE UNIQUE INDEX organization_delegations_ref_idx ON public.organization_delegations USING btree (delegation_ref);

CREATE INDEX organization_delegations_org_did_idx ON public.organization_delegations USING btree (organization_did, created_at);

CREATE INDEX organization_delegations_active_idx ON public.organization_delegations USING btree (organization_did) WHERE (revoked_at IS NULL);

CREATE UNIQUE INDEX collaboration_capability_grants_active_fingerprint_idx ON public.collaboration_capability_grants USING btree (subject, realm_id, action) WHERE (revoked_at IS NULL);

CREATE UNIQUE INDEX collaboration_capability_grants_capability_grant_id_idx ON public.collaboration_capability_grants USING btree (capability_grant_id);

CREATE UNIQUE INDEX collaboration_capability_grants_grant_event_id_idx ON public.collaboration_capability_grants USING btree (grant_event_id);

CREATE UNIQUE INDEX collaboration_capability_grants_revoke_event_id_idx ON public.collaboration_capability_grants USING btree (revoke_event_id) WHERE (revoke_event_id IS NOT NULL);

CREATE INDEX collaboration_capability_grants_active_realm_subject_idx ON public.collaboration_capability_grants USING btree (realm_id, subject, granted_at) WHERE (revoked_at IS NULL);

CREATE INDEX collaboration_capability_grants_revoked_idx ON public.collaboration_capability_grants USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);

CREATE INDEX handle_audit_log_event_idx ON public.handle_audit_log USING btree (event_type, created_at DESC);

CREATE INDEX handle_audit_log_user_idx ON public.handle_audit_log USING btree (user_id, created_at DESC);

CREATE INDEX idx_principal_did_bindings_user_id ON public.principal_did_bindings USING btree (user_id);

CREATE INDEX idx_principal_did_owners_user_id ON public.principal_did_owners USING btree (user_id);

CREATE INDEX idx_account_handoff_grants_account_audience ON public.account_handoff_grants USING btree (service_account_id, audience);

CREATE INDEX idx_account_handoff_grants_expiry ON public.account_handoff_grants USING btree (expires_at) WHERE ((revoked_at IS NULL) AND (consumed_at IS NULL));

CREATE INDEX idx_identity_creation_leases_expiry ON public.identity_creation_leases USING btree (expires_at) WHERE (state <> 'bound'::text);

CREATE INDEX idx_identity_binding_challenges_reservation ON public.identity_binding_challenges USING btree (service_account_id, audience, lease_id, lease_fence, operation_digest);

CREATE INDEX idx_identity_binding_challenges_expiry ON public.identity_binding_challenges USING btree (expires_at) WHERE ((consumed_at IS NULL) AND (replaced_at IS NULL));

CREATE INDEX idx_user_totp_configs_user_id ON public.user_totp_configs USING btree (user_id);

CREATE INDEX invite_quarantine_queue_consent_id_idx ON public.invite_quarantine_queue USING btree (consent_id);

CREATE INDEX invite_quarantine_queue_holder_did_idx ON public.invite_quarantine_queue USING btree (target_holder_did);

CREATE INDEX invite_quarantine_queue_status_created_idx ON public.invite_quarantine_queue USING btree (status, created_at DESC);

CREATE INDEX notification_deliveries_provider_binding_idx ON public.notification_deliveries USING btree (provider_binding_key) WHERE (provider_binding_key IS NOT NULL);

CREATE UNIQUE INDEX notification_deliveries_provider_message_lookup ON public.notification_deliveries USING btree (provider_binding_key, provider_message_id) WHERE ((provider_binding_key IS NOT NULL) AND (provider_message_id IS NOT NULL));

CREATE INDEX notification_deliveries_request_idx ON public.notification_deliveries USING btree (notification_request_id, id);

CREATE INDEX notification_deliveries_status_retry_idx ON public.notification_deliveries USING btree (status, next_retry_at, created_at, id);

CREATE INDEX notification_event_logs_delivery_idx ON public.notification_event_logs USING btree (notification_delivery_id, id) WHERE (notification_delivery_id IS NOT NULL);

CREATE INDEX notification_event_logs_request_idx ON public.notification_event_logs USING btree (notification_request_id, id);

CREATE UNIQUE INDEX notification_preferences_user_channel_idx ON public.notification_preferences USING btree (user_id, channel);

CREATE UNIQUE INDEX notification_requests_dedupe_key_idx ON public.notification_requests USING btree (dedupe_key) WHERE (dedupe_key IS NOT NULL);

CREATE INDEX notification_requests_status_scheduled_idx ON public.notification_requests USING btree (status, scheduled_at, id);

CREATE INDEX notification_template_versions_key_channel_idx ON public.notification_template_versions USING btree (template_key, channel);

CREATE UNIQUE INDEX notification_template_versions_key_version_channel_idx ON public.notification_template_versions USING btree (template_key, version, channel);

CREATE INDEX oauth_client_localized_metadata_client_idx ON public.oauth_client_localized_metadata USING btree (client_id);

CREATE INDEX oauth_refresh_tokens_chain_root_idx ON public.oauth_refresh_tokens USING btree (chain_root_oauth_refresh_token_id);

CREATE INDEX oauth_refresh_tokens_last_seen_idx ON public.oauth_refresh_tokens USING btree (last_seen_at);

CREATE INDEX oauth_session_grants_active_idx ON public.oauth_session_grants USING btree (expires_at) WHERE (revoked_at IS NULL);

CREATE INDEX oauth_session_grants_device_id_idx ON public.oauth_session_grants USING btree (device_id) WHERE (device_id IS NOT NULL);

CREATE INDEX oauth_session_grants_applet_delegation_active_idx ON public.oauth_session_grants USING btree (applet_id, registration_epoch, service_id, expires_at) WHERE ((revoked_at IS NULL) AND (applet_id IS NOT NULL));

CREATE INDEX oauth_session_grants_applet_effective_scope_idx ON public.oauth_session_grants USING gin (effective_scope) WHERE (effective_scope IS NOT NULL);

CREATE UNIQUE INDEX oauth_session_grants_grant_jwt_idx ON public.oauth_session_grants USING btree (grant_jwt);

CREATE UNIQUE INDEX oauth_session_grants_grant_id_idx ON public.oauth_session_grants USING btree (grant_id);

CREATE INDEX oauth_session_grants_subject_idx ON public.oauth_session_grants USING btree (subject);

CREATE INDEX oauth_session_grants_user_session_idx ON public.oauth_session_grants USING btree (user_session_id);

CREATE INDEX risk_action_proposals_account_idx ON public.risk_action_proposals USING btree (account_id, created_at DESC);

CREATE INDEX risk_action_proposals_state_idx ON public.risk_action_proposals USING btree (state);

CREATE INDEX user_primary_handle_preferences_as_of_idx ON public.user_primary_handle_preferences USING btree (user_id, effective_at DESC);

CREATE UNIQUE INDEX user_primary_handle_preferences_current_idx ON public.user_primary_handle_preferences USING btree (user_id) WHERE (replaced_at IS NULL);

CREATE INDEX user_primary_handle_preferences_handle_idx ON public.user_primary_handle_preferences USING btree (handle) WHERE (handle IS NOT NULL);

CREATE INDEX webauthn_credentials_account_idx ON public.webauthn_credentials USING btree (account_id, created_at DESC) WHERE (revoked_at IS NULL);

CREATE UNIQUE INDEX webauthn_credentials_credential_idx ON public.webauthn_credentials USING btree (credential_id);

CREATE INDEX workflow_audit_logs_instance_idx ON public.workflow_audit_logs USING btree (workflow_instance_id, id);

CREATE INDEX workflow_deadlines_status_due_idx ON public.workflow_deadlines USING btree (status, due_at);

CREATE INDEX workflow_events_instance_idx ON public.workflow_events USING btree (workflow_instance_id, id);

CREATE INDEX workflow_instances_correlation_key_idx ON public.workflow_instances USING btree (correlation_key) WHERE (correlation_key IS NOT NULL);

CREATE INDEX workflow_instances_key_status_idx ON public.workflow_instances USING btree (workflow_key, status);

CREATE INDEX workflow_instances_status_expires_idx ON public.workflow_instances USING btree (status, expires_at) WHERE (expires_at IS NOT NULL);

CREATE INDEX workflow_steps_instance_sequence_idx ON public.workflow_steps USING btree (workflow_instance_id, sequence);

CREATE TRIGGER handle_audit_log_no_delete BEFORE DELETE ON public.handle_audit_log FOR EACH ROW EXECUTE FUNCTION public.handle_audit_log_block_mutation();

CREATE TRIGGER handle_audit_log_no_update BEFORE UPDATE ON public.handle_audit_log FOR EACH ROW EXECUTE FUNCTION public.handle_audit_log_block_mutation();

ALTER TABLE ONLY public.account_claims
    ADD CONSTRAINT account_claims_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_email_authentications
    ADD CONSTRAINT fk_email_auth_registration FOREIGN KEY (user_registration_id) REFERENCES public.user_registrations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_phone_authentications
    ADD CONSTRAINT fk_phone_auth_registration FOREIGN KEY (user_registration_id) REFERENCES public.user_registrations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.queue_schedules
    ADD CONSTRAINT fk_schedule_last_job FOREIGN KEY (last_scheduled_job_id) REFERENCES public.queue_jobs(id);

ALTER TABLE ONLY public.handle_audit_log
    ADD CONSTRAINT handle_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_notification_request_id_fkey FOREIGN KEY (notification_request_id) REFERENCES public.notification_requests(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notification_event_logs
    ADD CONSTRAINT notification_event_logs_notification_delivery_id_fkey FOREIGN KEY (notification_delivery_id) REFERENCES public.notification_deliveries(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notification_event_logs
    ADD CONSTRAINT notification_event_logs_notification_request_id_fkey FOREIGN KEY (notification_request_id) REFERENCES public.notification_requests(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_oauth_session_id_fkey FOREIGN KEY (oauth_session_id) REFERENCES public.oauth_sessions(id);

ALTER TABLE ONLY public.oauth_authorization_grants
    ADD CONSTRAINT oauth_authorization_grants_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES public.oauth_clients(id);

ALTER TABLE ONLY public.oauth_authorization_grants
    ADD CONSTRAINT oauth_authorization_grants_oauth_session_id_fkey FOREIGN KEY (oauth_session_id) REFERENCES public.oauth_sessions(id);

ALTER TABLE ONLY public.oauth_client_localized_metadata
    ADD CONSTRAINT oauth_client_localized_metadata_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.oauth_clients(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES public.oauth_clients(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_oauth_session_id_fkey FOREIGN KEY (oauth_session_id) REFERENCES public.oauth_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_device_code_grant
    ADD CONSTRAINT oauth_device_code_grant_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id);

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_next_oauth_refresh_token_id_fkey FOREIGN KEY (next_oauth_refresh_token_id) REFERENCES public.oauth_refresh_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_oauth_access_token_id_fkey FOREIGN KEY (oauth_access_token_id) REFERENCES public.oauth_access_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_oauth_session_id_fkey FOREIGN KEY (oauth_session_id) REFERENCES public.oauth_sessions(id);

ALTER TABLE ONLY public.oauth_session_grants
    ADD CONSTRAINT oauth_session_grants_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_sessions
    ADD CONSTRAINT oauth_sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES public.oauth_clients(id);

ALTER TABLE ONLY public.oauth_sessions
    ADD CONSTRAINT oauth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_sessions
    ADD CONSTRAINT oauth_sessions_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_personal_session_id_fkey FOREIGN KEY (personal_session_id) REFERENCES public.personal_sessions(id);

ALTER TABLE ONLY public.personal_sessions
    ADD CONSTRAINT personal_sessions_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.personal_sessions
    ADD CONSTRAINT personal_sessions_owner_oauth_client_id_fkey FOREIGN KEY (owner_oauth_client_id) REFERENCES public.oauth_clients(id);

ALTER TABLE ONLY public.personal_sessions
    ADD CONSTRAINT personal_sessions_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.principal_did_bindings
    ADD CONSTRAINT principal_did_bindings_owner_user_fkey FOREIGN KEY (principal_did_owner_id, user_id) REFERENCES public.principal_did_owners(id, user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.principal_did_owners
    ADD CONSTRAINT principal_did_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.account_handoff_grants
    ADD CONSTRAINT account_handoff_grants_service_account_id_fkey FOREIGN KEY (service_account_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.account_handoff_grants
    ADD CONSTRAINT account_handoff_grants_browser_session_id_fkey FOREIGN KEY (browser_session_id) REFERENCES public.user_sessions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.identity_creation_leases
    ADD CONSTRAINT identity_creation_leases_service_account_id_fkey FOREIGN KEY (service_account_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.identity_binding_challenges
    ADD CONSTRAINT identity_binding_challenges_service_account_id_fkey FOREIGN KEY (service_account_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.queue_jobs
    ADD CONSTRAINT queue_jobs_next_attempt_id_fkey FOREIGN KEY (next_attempt_id) REFERENCES public.queue_jobs(id);

ALTER TABLE ONLY public.queue_jobs
    ADD CONSTRAINT queue_jobs_schedule_name_fkey FOREIGN KEY (schedule_name) REFERENCES public.queue_schedules(schedule_name);

ALTER TABLE ONLY public.queue_jobs
    ADD CONSTRAINT queue_jobs_started_by_fkey FOREIGN KEY (started_by) REFERENCES public.queue_workers(id);

ALTER TABLE ONLY public.queue_leader
    ADD CONSTRAINT queue_leader_queue_worker_id_fkey FOREIGN KEY (queue_worker_id) REFERENCES public.queue_workers(id);

ALTER TABLE ONLY public.risk_action_proposals
    ADD CONSTRAINT risk_action_proposals_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.upstream_oauth_authorization_sessions
    ADD CONSTRAINT upstream_oauth_authorization_se_upstream_oauth_provider_id_fkey FOREIGN KEY (upstream_oauth_provider_id) REFERENCES public.upstream_oauth_providers(id);

ALTER TABLE ONLY public.upstream_oauth_authorization_sessions
    ADD CONSTRAINT upstream_oauth_authorization_sessio_upstream_oauth_link_id_fkey FOREIGN KEY (upstream_oauth_link_id) REFERENCES public.upstream_oauth_links(id);

ALTER TABLE ONLY public.upstream_oauth_authorization_sessions
    ADD CONSTRAINT upstream_oauth_authorization_sessions_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.upstream_oauth_links
    ADD CONSTRAINT upstream_oauth_links_upstream_oauth_provider_id_fkey FOREIGN KEY (upstream_oauth_provider_id) REFERENCES public.upstream_oauth_providers(id);

ALTER TABLE ONLY public.upstream_oauth_links
    ADD CONSTRAINT upstream_oauth_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_email_authentication_codes
    ADD CONSTRAINT user_email_authentication_cod_user_email_authentication_id_fkey FOREIGN KEY (user_email_authentication_id) REFERENCES public.user_email_authentications(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_email_authentications
    ADD CONSTRAINT user_email_authentications_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_emails
    ADD CONSTRAINT user_emails_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_passwords
    ADD CONSTRAINT user_passwords_upgraded_from_id_fkey FOREIGN KEY (upgraded_from_id) REFERENCES public.user_passwords(id);

ALTER TABLE ONLY public.user_passwords
    ADD CONSTRAINT user_passwords_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_phone_authentication_codes
    ADD CONSTRAINT user_phone_authentication_cod_user_phone_authentication_id_fkey FOREIGN KEY (user_phone_authentication_id) REFERENCES public.user_phone_authentications(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_phones
    ADD CONSTRAINT user_phones_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_primary_handle_preferences
    ADD CONSTRAINT user_primary_handle_preferences_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_primary_handle_preferences
    ADD CONSTRAINT user_primary_handle_preferences_source_claim_id_fkey FOREIGN KEY (source_claim_id) REFERENCES public.handle_audit_log(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_primary_handle_preferences
    ADD CONSTRAINT user_primary_handle_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_recovery_tickets
    ADD CONSTRAINT user_recovery_tickets_user_email_id_fkey FOREIGN KEY (user_email_id) REFERENCES public.user_emails(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_recovery_tickets
    ADD CONSTRAINT user_recovery_tickets_user_recovery_session_id_fkey FOREIGN KEY (user_recovery_session_id) REFERENCES public.user_recovery_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_registrations
    ADD CONSTRAINT user_registrations_email_authentication_id_fkey FOREIGN KEY (email_authentication_id) REFERENCES public.user_email_authentications(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_registrations
    ADD CONSTRAINT user_registrations_phone_authentication_id_fkey FOREIGN KEY (phone_authentication_id) REFERENCES public.user_phone_authentications(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_registrations
    ADD CONSTRAINT user_registrations_upstream_oauth_authorization_session_id_fkey FOREIGN KEY (upstream_oauth_authorization_session_id) REFERENCES public.upstream_oauth_authorization_sessions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_registrations
    ADD CONSTRAINT user_registrations_user_registration_token_id_fkey FOREIGN KEY (user_registration_token_id) REFERENCES public.user_registration_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_session_authentications
    ADD CONSTRAINT user_session_authentications_upstream_oauth_authorization__fkey FOREIGN KEY (upstream_oauth_authorization_session_id) REFERENCES public.upstream_oauth_authorization_sessions(id);

ALTER TABLE ONLY public.user_session_authentications
    ADD CONSTRAINT user_session_authentications_user_password_id_fkey FOREIGN KEY (user_password_id) REFERENCES public.user_passwords(id);

ALTER TABLE ONLY public.user_session_authentications
    ADD CONSTRAINT user_session_authentications_user_session_id_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id);

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_terms
    ADD CONSTRAINT user_terms_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_totp_configs
    ADD CONSTRAINT user_totp_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_unsupported_third_party_ids
    ADD CONSTRAINT user_unsupported_third_party_ids_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.webauthn_credentials
    ADD CONSTRAINT webauthn_credentials_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_audit_logs
    ADD CONSTRAINT workflow_audit_logs_workflow_instance_id_fkey FOREIGN KEY (workflow_instance_id) REFERENCES public.workflow_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_audit_logs
    ADD CONSTRAINT workflow_audit_logs_workflow_step_id_fkey FOREIGN KEY (workflow_step_id) REFERENCES public.workflow_steps(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_deadlines
    ADD CONSTRAINT workflow_deadlines_workflow_instance_id_fkey FOREIGN KEY (workflow_instance_id) REFERENCES public.workflow_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_deadlines
    ADD CONSTRAINT workflow_deadlines_workflow_step_id_fkey FOREIGN KEY (workflow_step_id) REFERENCES public.workflow_steps(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_events
    ADD CONSTRAINT workflow_events_workflow_instance_id_fkey FOREIGN KEY (workflow_instance_id) REFERENCES public.workflow_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_events
    ADD CONSTRAINT workflow_events_workflow_step_id_fkey FOREIGN KEY (workflow_step_id) REFERENCES public.workflow_steps(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.workflow_steps
    ADD CONSTRAINT workflow_steps_workflow_instance_id_fkey FOREIGN KEY (workflow_instance_id) REFERENCES public.workflow_instances(id) ON DELETE CASCADE;
