[book]
title = "coauth 文档"
authors = ["chris@sonc.ai"]
language = "zh"
src = "../docs/zh"

[build]
build-dir = "../target/book/zh"

[output.html]
edit-url-template = "https://github.com/arkret-org/coauth/edit/main/{path}"
git-repository-url = "https://github.com/arkret-org/coauth"
site-url = "/coauth/zh/"
