//! coauth backend — HTTP server, state management, lifecycle, and telemetry.
//!
//! This crate provides the runtime infrastructure for the Arkret Auth /
//! Account Server. It is consumed by the CLI binary (`coauth`) and can
//! also be embedded as a library.

// The workspace clippy policy disallows `chrono::Utc::now`, `Ulid::new`,
// and direct `reqwest::RequestBuilder::send` in favour of injected
// abstractions. Many sites in this crate (and especially in tests) use
// the raw APIs; threading abstractions through every caller is a
// separate refactor, so the lints are silenced at the crate level.
#![allow(clippy::disallowed_methods)]

pub mod app_state;
/// The one place where `ed25519-dalek` 2.x (JOSE/keyring) and `ed25519-dalek`
/// 3.x (Arkret SDK) keys convert into each other.
pub mod arkret_key_bridge;
pub mod error;
pub mod lifecycle;
/// Network listener infrastructure: TCP/Unix sockets, TLS, and PROXY protocol.
pub mod listener;
/// OpenID Connect client library.
pub mod oidc_client;
mod outbound_http;
/// Policy evaluation abstraction layer; the shipped backend is Cedar.
pub mod policy;
/// Salvo web-framework utilities: middleware, extractors, and helpers.
pub mod salvo_utils;
pub mod server;
pub mod services;
pub mod storage;
pub mod sync;
pub mod telemetry;
pub mod util;

/// HTTP request handlers, service modules, and journey engine.
#[allow(
    // Some salvo handlers need that
    clippy::unused_async,
    // Because of how salvo handlers work, we sometime have take many arguments
    clippy::too_many_arguments,
    // Code generated by tracing::instrument trigger this when returning an `impl Trait`
    // See https://github.com/tokio-rs/tracing/issues/2613
    clippy::let_with_type_underscore,
)]
pub mod handlers;

use std::sync::OnceLock;

pub use crate::error::{AppError, AppResult, CreatedJsonResult, JsonResult};
pub use crate::outbound_http::{
    RequestBuilderExt, reqwest_client, reqwest_client_for_arkret, reqwest_client_for_server,
};

/// Application version string, set once at startup by the binary crate.
static VERSION: OnceLock<&'static str> = OnceLock::new();

/// Set the application version string.
///
/// Must be called exactly once, before any code that reads `version()`.
/// Typically called from `main()` in the CLI binary.
///
/// # Panics
///
/// Panics if called more than once.
pub fn set_version(v: &'static str) {
    VERSION
        .set(v)
        .expect("coauth_backend::set_version called more than once");
}

/// Get the application version string.
///
/// # Panics
///
/// Panics if [`set_version`] has not been called yet.
pub fn version() -> &'static str {
    VERSION
        .get()
        .expect("coauth_backend::set_version was not called")
}
