[package]
name = "coauth-data"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
coauth-account-types = {workspace = true}
async-trait = {workspace = true}
chrono = {workspace = true}
coauth-email-types = {workspace = true}
coauth-data-model = {workspace = true}
coauth-iana = {workspace = true}
coauth-jose = {workspace = true}
arkret-locale = {workspace = true,features = ["serde"]}
arkret-canonical = {workspace = true}
arkret-identifiers = {workspace = true}
arkret-models-collaboration = {workspace = true}
arkret-models-identity = {workspace = true}
arkret-wire = {workspace = true}
crc = {workspace = true}
futures-util = {workspace = true}
language-tags = {workspace = true}
coauth-oauth-types = {workspace = true}
opentelemetry = {workspace = true}
rand_chacha = {workspace = true}
rand_core = {workspace = true}
regex = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}
tracing = {workspace = true}
tracing-opentelemetry = {workspace = true}
ulid = {workspace = true}
url = {workspace = true}
uuid = {workspace = true}
woothee = {workspace = true}
soland-contracts = {workspace = true}
