name: Documentation Pipeline

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  CARGO_TERM_COLOR: always

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-docs:
    name: Generate documentation site
    runs-on: ubuntu-24.04

    steps:
      - name: Fetch repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable

      - name: Configure sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Set up mdbook
        uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2
        with:
          tool: mdbook

      - name: Generate documentation output
        run: mdbook build

      - name: Adjust file permissions for deployment
        run: |
          chmod -c -R +rX "target/book/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Store pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: target/book/

  publish-docs:
    name: Publish to GitHub Pages
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: compile-docs

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.pages-deploy.outputs.page_url }}

    steps:
      - name: Publish pages
        id: pages-deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
